/* EWT Garden — kho đặc sản (phần A): 9 khu cơ bản — Vườn nhà Tom, Đồi gió, Bờ sông, Hồ sen, Rừng chòi lá, Cung điện hoa, Vườn mùa đông, Khu biển, Khu phép thuật. */
(function (root) {
  'use strict';
  var Cat = root.EWTGardenCatalog || (typeof require === 'function' ? require('./garden-catalog.js') : null); if (!Cat) return;
  var P = function (n, a, c, d, acc, x) { return [n, a, c, d, acc, x]; };

  Cat.add('cottage', { map: {},
    f: [['Cúc vàng sân nhà', 'daisy', '#FFD23F', '#E58A1B', 1], ['Tulip hồng phấn', 'cup', '#FF8FB8', '#FFD23F', 1], ['Chuông xanh đầu hè', 'bell', '#6AA4F2', '#FFFFFF', 2], ['Oải hương tím', 'spike', '#B48CFF', '#7A4ACF', 2], ['Mẫu đơn nhà vườn', 'pom', '#FF9EC4', '#FFD23F', 3]],
    t: [['Táo đỏ sau nhà', 'round', '#4FAE4A', '#E23B3B', 2, { fruit: 1 }], ['Anh đào sân vườn', 'blossom', '#FFC4D8', '#FF7FAE', 3], ['Phong vàng mùa thu', 'maple', '#F2A32C', '#E2531F', 3], ['Sồi nhỏ trước ngõ', 'round', '#3C8A3E', '#B8733A', 2, { fruit: 1 }], ['Bách thanh dáng cao', 'cypress', '#3C8A4A', '#FFD23F', 4]],
    d: [['Đèn sân vườn', 'lamp', 'star', '#E8541E', '#FFE9A8', 1], ['Chậu hoa gỗ', 'planter', 'flower', '#B8733A', '#FF8FB8', 1], ['Ghế đá sân nhà', 'bench', 'leaf', '#8A9AA8', '#4FAE4A', 2], ['Cổng vòm hoa hồng', 'arch', 'heart', '#E8D4B0', '#FF6B8A', 3], ['Giếng nước nhà Tom', 'well', 'drop', '#C9503A', '#5AA8F0', 3]],
    b: [['Nhà kính hoa', 3, 2, 'house', '#CDEFF5', '#7FB8C8', '#4FAE4A', 'flowers', 2], ['Chòi hóng mát', 2, 2, 'pavilion', '#E8D4B0', '#C9503A', '#F2C94C', '', 2], ['Nhà kho gỗ', 2, 2, 'barn', '#C98A4B', '#8A3A2A', '#FFFFFF', '', 1], ['Tháp đồng hồ vườn', 2, 3, 'tower', '#F2E8D0', '#6B8A7A', '#F2C94C', 'flag', 3], ['Nhà búp bê', 2, 2, 'house', '#FFD9E6', '#E85A8A', '#8A5A2E', 'balcony+bunting', 4]],
    p: [['Mèo mướp', 'cat', '#C9A66A', '#FFF1DE', '', 1], ['Cún vàng', 'dog', '#E8C79A', '#FFF1DE', 'bow', 1], ['Chim sẻ nâu', 'bird', '#B8844A', '#F2E8D8', '', 1], ['Thỏ nơ hồng', 'bunny', '#FFFFFF', '#FFC9D4', 'bow', 2], ['Hamster đội mũ', 'mouse', '#E8C08A', '#FFF1DE', 'hat', 3]] });

  Cat.add('hill', { map: { d: ['windmill'] },
    f: [['Cúc dại đồi gió', 'daisy', '#FFFFFF', '#F2A32C', 1], ['Chuông đồi tím', 'bell', '#9A7BE8', '#FFFFFF', 2], ['Cỏ bông lau', 'plume', '#F2E8C8', '#D8C58A', 2], ['Anh túc đỏ', 'poppy', '#E8431F', '#2E2A33', 3], ['Phong lữ hồng', 'pom', '#FF7FAE', '#FFD6E5', 3]],
    t: [['Thông gió đồi', 'conifer', '#3C8A5A', '#FFD23F', 2], ['Bạch dương trắng', 'birch', '#9AD07A', '#F2C94C', 2], ['Sồi cổ đồi', 'round', '#4A9A46', '#B8733A', 3, { fruit: 1 }], ['Liễu rủ trước gió', 'willow', '#7FC27A', '#FFE36B', 4], ['Táo dại', 'round', '#6FBA5A', '#E8543A', 3, { fruit: 1 }]],
    d: [['Cờ phướn gió', 'banner', 'cloud', '#4FB4FF', '#FFFFFF', 1], ['Đá chồng trên đồi', 'cairn', 'leaf', '#C9D0D9', '#4FAE4A', 2], ['Biển chỉ đường đồi', 'sign', 'mountain', '#C98A4B', '#4F6AA8', 2], ['Diều thần', 'banner', 'diamond', '#FF6B8A', '#FFD23F', 3]],
    b: [['Cối xay gió lớn', 3, 3, 'mill', '#F2E8D0', '#C9503A', '#F2C94C', 'flag', 4], ['Nhà mục đồng', 2, 2, 'hut', '#D8C58A', '#A8761F', '#8A5A2E', 'smoke', 2], ['Trang trại gió', 3, 2, 'barn', '#D9534A', '#6B4A2B', '#FFFFFF', 'chimney', 3], ['Tháp quan sát đồi', 2, 3, 'tower', '#C9BFA4', '#6B8A7A', '#F2C94C', 'flag', 3], ['Nhà gỗ trên đồi', 3, 2, 'house', '#E8D4B0', '#8A5A2E', '#C9503A', 'chimney+flowers', 3]],
    p: [['Chó chăn cừu', 'dog', '#2A2A34', '#FFFFFF', '', 2], ['Dê đồi sừng cong', 'hoof', '#E8E2D0', '#B8733A', 'horns', 3], ['Ngựa hoang bờm nâu', 'hoof', '#C98A4B', '#6B4A2B', '', 3], ['Chim ưng đồi', 'bird', '#8A6A44', '#F2E8D0', 'glow', 4], ['Thỏ rừng', 'bunny', '#C9A66A', '#F2E8D0', 'leaf', 2]] });

  Cat.add('river', { map: { b: ['bridge'] },
    f: [['Sậy ven sông', 'reed', '#8A5A2E', '#6FA85A', 1], ['Lau sậy bạc', 'plume', '#EAF2F8', '#B8D0E0', 2], ['Hoa súng xanh', 'lotus', '#7FB8F2', '#FFE36B', 3], ['Iris nước', 'orchid', '#8A6AE8', '#FFD23F', 3], ['Hoa dạ yến', 'lily', '#FFB8D0', '#E8856A', 4]],
    t: [['Liễu ven nước', 'willow', '#7FCB7A', '#FFFFFF', 2], ['Tràm bông vàng', 'round', '#5FA860', '#FFD23F', 2, { fruit: 1 }], ['Dừa nước', 'palm', '#3C9A52', '#8A5A2E', 3], ['Đước rễ chống', 'mangrove', '#3C8A4A', '#E8B84A', 4], ['Phi lao gió sông', 'conifer', '#5FA070', '#FFFFFF', 3]],
    d: [['Phao cứu hộ', 'barrel', 'anchor', '#E23B3B', '#FFFFFF', 1], ['Cọc neo thuyền', 'obelisk', 'anchor', '#8A5A2E', '#C9D0D9', 2], ['Thuyền gỗ nhỏ', 'boat', 'wave', '#B8733A', '#5AA8F0', 2], ['Đèn bến sông', 'lamp', 'fish', '#3B6EA8', '#FFE9A8', 3], ['Bia cá hồi', 'sign', 'fish', '#C98A4B', '#5AA8F0', 3]],
    b: [['Bến thuyền gỗ', 3, 2, 'dock', '#C98A4B', '#6B4A2B', '#E23B3B', 'flag', 3], ['Nhà bè nổi', 3, 2, 'stilt', '#D8B070', '#8A5A2E', '#2E7D4F', 'lantern', 3], ['Trạm cứu hộ sông', 2, 2, 'house', '#FFFFFF', '#E23B3B', '#4FB4FF', 'flag', 2], ['Cối xay nước', 3, 2, 'mill', '#E8D4B0', '#8A5A2E', '#5AA8F0', 'vines', 3]],
    p: [['Vịt trời', 'duck', '#7A8A5A', '#F2B632', '', 1], ['Ếch xanh', 'frog', '#6FBA5A', '#E8F2C8', '', 1], ['Rùa sông', 'turtle', '#5A8A4A', '#C9A66A', '', 2], ['Cá chép đỏ', 'fish', '#FF6B3A', '#FFD23F', 'spots', 3], ['Rái cá', 'seal', '#8A5A3A', '#E8D4B0', 'scarf', 4]] });

  Cat.add('pond', { map: { f: ['lotus'], d: ['pond'], b: ['pondbig'] },
    f: [['Sen hồng phấn hồ', 'lotus', '#FF9EC4', '#FFE36B', 3], ['Súng tím', 'lotus', '#B48CFF', '#FFD23F', 3], ['Bèo hoa dâu', 'fern', '#7FD36B', '#4FAE4A', 2], ['Hoa thủy tiên nước', 'star', '#FFFFFF', '#FFD23F', 2]],
    t: [['Liễu hồ', 'willow', '#8ED08A', '#FFFFFF', 2], ['Trúc nước', 'cypress', '#6FBA5A', '#F2C94C', 2], ['Hồng hoa mai ven hồ', 'blossom', '#FFB7D0', '#FF8FB8', 3], ['Tùng la hán', 'conifer', '#3C8A5A', '#E8B84A', 3], ['Cây bồ đề cổ', 'round', '#4F9A5A', '#F2C94C', 4, { fruit: 1 }]],
    d: [['Đèn nước hoa sen', 'lamp', 'lotus', '#E8854A', '#FFE9A8', 2], ['Cầu đá cong', 'arch', 'wave', '#C9D0D9', '#5AA8F0', 3], ['Tượng cá chép hóa rồng', 'pedestal', 'fish', '#C9D0D9', '#FF8A3D', 3], ['Chuông gió hồ', 'gong', 'bell', '#B8861B', '#F2C94C', 4]],
    b: [['Chòi nghỉ chân mái lá', 2, 2, 'hut', '#D8C58A', '#A8761F', '#8A5A2E', 'lantern', 2], ['Đình giữa hồ', 3, 2, 'pavilion', '#C9503A', '#2E7D4F', '#F2C94C', 'lantern', 3], ['Cầu gỗ thủy tạ', 3, 2, 'dock', '#C98A4B', '#6B4A2B', '#E23B3B', '', 3], ['Nhà thuyền hồ sen', 3, 2, 'ship', '#B8733A', '#FFF8E8', '#E23B3B', '', 4]],
    p: [['Cá koi đỏ trắng', 'fish', '#FFFFFF', '#E23B3B', 'spots', 3], ['Ếch hồ sen', 'frog', '#8ED08A', '#FFE9A8', 'leaf', 2], ['Vịt uyên ương', 'duck', '#FF9A3A', '#2E7D4F', '', 3], ['Sếu trắng', 'bird', '#FFFFFF', '#2A2A34', 'crown', 4], ['Rùa tai đỏ', 'turtle', '#4F8A4A', '#E23B3B', '', 2]] });

  Cat.add('forest', { map: { b: ['hutbig', 'cabinbig'] },
    f: [['Nấm rừng đỏ', 'shroom', '#E5334B', '#FFFFFF', 2], ['Dương xỉ rừng', 'fern', '#4FAE4A', '#2F8A4A', 1], ['Chuông rừng xanh', 'bell', '#4F7AE8', '#FFFFFF', 2], ['Quả mọng đỏ', 'berry', '#D93A5A', '#3C9A4C', 3], ['Hoa tai rừng', 'orchid', '#E8A8D8', '#FFD23F', 4]],
    t: [['Thông rừng già', 'conifer', '#2F7A4A', '#E8B84A', 2], ['Sồi cổ thụ rừng', 'round', '#3C7A3E', '#B8733A', 3, { fruit: 1 }], ['Bạch dương rừng', 'birch', '#8FCB6A', '#F2C94C', 2], ['Phong đỏ rừng', 'maple', '#C4321C', '#F2A32C', 3], ['Cây nấm khổng lồ', 'shroomtree', '#C9503A', '#FFFFFF', 4]],
    d: [['Đống lửa trại', 'chest', 'flame', '#8A5A2E', '#FF8A2A', 2], ['Khúc gỗ ngồi', 'barrel', 'leaf', '#B8733A', '#6B4A2B', 1], ['Lều dã ngoại', 'tent', 'star', '#4F8A5A', '#F2C94C', 2], ['Biển chỉ đường rừng', 'sign', 'paw', '#8A5A2E', '#F2E8D0', 2], ['Đèn dầu treo cây', 'lamp', 'leaf', '#3B4252', '#FFE9A8', 3]],
    b: [['Nhà cây trên cành', 2, 2, 'stilt', '#C98A4B', '#3C8A4A', '#F2C94C', 'vines', 3], ['Chòi canh rừng', 2, 3, 'tower', '#B8733A', '#6B4A2B', '#E23B3B', 'flag', 3], ['Nhà gỗ thợ săn', 3, 2, 'house', '#B8733A', '#6B4A2B', '#8A5A2E', 'chimney+smoke', 3]],
    p: [['Cú mèo rừng', 'owl', '#8A6A44', '#E8D4B0', '', 2], ['Sóc rừng đuôi xù', 'mouse', '#B8733A', '#FFF1DE', 'leaf', 2], ['Nai con', 'hoof', '#C98A4B', '#FFF1DE', 'spots', 3], ['Gấu nâu con', 'bear', '#8A5A3A', '#E8C79A', '', 3], ['Cáo đuôi lửa', 'fox', '#F2793A', '#FFFFFF', 'flame', 5]] });

  Cat.add('palace', { map: { d: ['fountain'], b: ['castle', 'fountainbig', 'flowerarch', 'gazebo', 'clocktower'] },
    f: [['Hồng nhung hoàng gia', 'poppy', '#B8143A', '#FFD23F', 3], ['Huệ trắng cung đình', 'lily', '#FFFFFF', '#F2C94C', 3], ['Mẫu đơn hoàng kim', 'pom', '#FFD23F', '#E8854A', 4], ['Lan hoàng yến', 'orchid', '#F2C94C', '#B8861B', 4], ['Tử đinh hương', 'spike', '#B48CFF', '#7A4ACF', 2]],
    t: [['Tử đằng vương giả', 'willow', '#B48CFF', '#F2C94C', 3], ['Bách tán cung điện', 'cypress', '#2F7A4A', '#F2C94C', 3], ['Cây cắt tỉa tròn', 'round', '#3C9A4A', '#FFD23F', 2], ['Hoa hồng leo', 'blossom', '#FF8FB8', '#E23B3B', 4], ['Cọ hoàng gia', 'palm', '#3FAE4A', '#F2C94C', 3]],
    d: [['Tượng thiên thần', 'pedestal', 'feather', '#F2F2F2', '#F2C94C', 4], ['Đèn chùm sân', 'lamp', 'crown', '#B8861B', '#FFE9A8', 3], ['Cổng sắt hoàng gia', 'arch', 'crown', '#3A3A44', '#F2C94C', 4], ['Lọ men cung đình', 'vase', 'diamond', '#2E6BD8', '#F2C94C', 3]],
    p: [['Thiên nga trắng', 'duck', '#FFFFFF', '#FF9A3A', 'crown', 4], ['Công xanh', 'bird', '#2E8B9A', '#F2C94C', 'wings', 5], ['Chó nhỏ cung đình', 'dog', '#FFFFFF', '#F2D9C8', 'bow', 3], ['Mèo Ba Tư', 'cat', '#F2E8D8', '#FFFFFF', 'crown', 4], ['Ngựa trắng hoàng tử', 'hoof', '#FFFFFF', '#E8D4B0', 'cape', 5]] });

  Cat.add('winter', { map: {},
    f: [['Hoa tuyết trắng', 'bell', '#FFFFFF', '#7FD36B', 1], ['Cúc tuyết', 'daisy', '#EAF4FF', '#7FB8E8', 1], ['Hoa băng giá', 'crystal', '#BFE8FF', '#7FB8E8', 3], ['Hồng tuyết', 'poppy', '#FFFFFF', '#E23B3B', 3], ['Hoa lạnh xanh', 'star', '#9AD0F2', '#FFFFFF', 2, 8]],
    t: [['Thông phủ tuyết', 'conifer', '#3C7A5A', '#E23B3B', 2, { snow: 1 }], ['Thông băng lấp lánh', 'icetree', '#BFE8FF', '#FFFFFF', 3], ['Bạch dương mùa đông', 'birch', '#EAF4FF', '#BFE8FF', 3], ['Sồi trụi lá', 'dead', '#6B5646', '#BFE8FF', 2], ['Thông Noel', 'conifer', '#2F8A5A', '#FFD23F', 4, { snow: 1 }]],
    d: [['Người tuyết mũ đỏ', 'pedestal', 'snow', '#FFFFFF', '#E23B3B', 2], ['Đèn tuyết rơi', 'lamp', 'snow', '#5A7AA8', '#FFF8C8', 2], ['Xe trượt tuyết gỗ', 'bench', 'star', '#C9503A', '#F2C94C', 3], ['Hộp quà Giáng sinh', 'chest', 'star', '#E23B3B', '#FFD23F', 3], ['Vòng hoa cửa', 'arch', 'snow', '#2F8A5A', '#E23B3B', 4]],
    b: [['Nhà gỗ ấm áp', 3, 2, 'house', '#C98A4B', '#FFFFFF', '#E23B3B', 'chimney+smoke+snow', 3], ['Quán cà phê tuyết', 2, 2, 'shop', '#F2D9B8', '#C9503A', '#8A5A2E', 'snow+bunting', 3], ['Sân trượt băng', 3, 2, 'pavilion', '#BFE8FF', '#7FB8E8', '#FFFFFF', 'icicles', 4], ['Lâu đài băng', 3, 3, 'castle', '#DDF2FF', '#7FB8E8', '#4FB4FF', 'icicles+snow', 5], ['Nhà thờ nhỏ trong tuyết', 2, 3, 'tower', '#F7EEDC', '#C9503A', '#F2C94C', 'snow', 4]],
    p: [['Thỏ tuyết', 'bunny', '#FFFFFF', '#BFE8FF', 'scarf', 2], ['Cáo tuyết', 'fox', '#F2F8FF', '#BFE8FF', 'scarf', 3], ['Cú tuyết', 'owl', '#FFFFFF', '#D8E8F4', '', 3], ['Chó kéo xe', 'dog', '#8A9AB0', '#FFFFFF', 'scarf', 3], ['Hươu tuần lộc', 'hoof', '#B8844A', '#F2E8D0', 'antlers', 4]] });

  Cat.add('beach', { map: { t: ['palm'] },
    f: [['Dâm bụt biển', 'poppy', '#FF5C7A', '#FFD23F', 2], ['Hoa muống biển', 'cup', '#E8A8F2', '#FFFFFF', 1], ['Hoa giấy bãi cát', 'paper', '#FF5CA8', '#FFD23F', 3], ['Xương rồng bãi biển', 'paddle', '#FF8FB8', '#6FBA5A', 3], ['Hải quỳ cạn', 'anemone', '#FF8A5A', '#FFD23F', 4]],
    t: [['Dừa cao', 'palm', '#3FAE4A', '#8A5A2E', 2], ['Dừa lùn trái vàng', 'palm', '#5FC25A', '#F2C94C', 3], ['Phi lao biển', 'conifer', '#5FA070', '#F2E8D0', 2], ['Bàng biển', 'umbrella', '#4FAE5A', '#F2A32C', 3]],
    d: [['Dù che nắng sọc', 'parasol', 'sun', '#FF6B5A', '#FFD23F', 1], ['Ghế tắm nắng', 'bench', 'shell', '#4FB4FF', '#FFFFFF', 2], ['Biển cấm bơi', 'sign', 'wave', '#E23B3B', '#FFFFFF', 2], ['Ván lướt sóng', 'banner', 'wave', '#3A9AE8', '#FFFFFF', 3], ['Tháp cứu hộ nhỏ', 'shrine', 'anchor', '#E23B3B', '#FFFFFF', 4]],
    b: [['Chòi dừa', 2, 2, 'hut', '#E8D4A0', '#D8A83A', '#8A5A2E', 'sand', 2], ['Quán nước biển', 3, 2, 'shop', '#4FB4FF', '#FFFFFF', '#FFD23F', 'bunting+sand', 3], ['Nhà sàn trên cát', 3, 2, 'stilt', '#F2D9A8', '#E8854A', '#2E8B9A', 'shells', 3], ['Bến tàu nhỏ', 3, 2, 'dock', '#C98A4B', '#6B4A2B', '#E23B3B', 'flag', 3], ['Hải đăng cát vàng', 2, 3, 'lighthouse', '#FFF8E8', '#E23B3B', '#F2C94C', 'flag', 5]],
    p: [['Cua cát', 'crab', '#F2A05A', '#FFD6A8', '', 2], ['Hải âu', 'bird', '#FFFFFF', '#9AB8C8', '', 2], ['Rùa biển', 'turtle', '#4F9A8A', '#C9E8C8', 'spots', 3], ['Cá heo xanh', 'whale', '#6FA8D8', '#EAF4FA', 'glow', 4], ['Hải cẩu bãi', 'seal', '#B8A89A', '#E8DED0', 'bow', 3]] });

  Cat.add('magic', { map: { f: ['moonflower', 'glowshroom'] },
    f: [['Hoa tiên tím', 'orchid', '#B48CFF', '#F2E8FF', 4], ['Hoa pha lê ma thuật', 'crystal', '#9AF2FF', '#B48CFF', 4], ['Hoa sao băng', 'star', '#FFE36B', '#FFFFFF', 3, 8]],
    t: [['Cây hồn nhiên lấp lánh', 'blossom', '#C9A8FF', '#FFFFFF', 3], ['Cây sương mù tím', 'willow', '#9A7BE8', '#FFE36B', 3], ['Cây pha lê đêm', 'crystal', '#B48CFF', '#7AF2FF', 4], ['Cây nấm thần', 'shroomtree', '#8E5CF0', '#FFE36B', 4], ['Cây gậy phép', 'cypress', '#6A4CC0', '#FFE36B', 3]],
    d: [['Quả cầu tiên tri', 'pedestal', 'eye', '#6A4CC0', '#9AF2FF', 4], ['Vạc phép thuật', 'barrel', 'flame', '#3A3A44', '#7AF2A0', 3], ['Đèn ma trơi', 'lamp', 'moon', '#4A3A8A', '#9AF2FF', 3], ['Cổng pháp trận', 'arch', 'star', '#6A4CC0', '#FFE36B', 4], ['Sách phép cổ', 'chest', 'spiral', '#6A3A8A', '#F2C94C', 3]],
    b: [['Tháp pháp sư nhỏ', 2, 3, 'tower', '#6A4CC0', '#2E1F72', '#FFE36B', 'stars', 3], ['Lâu đài ma thuật', 3, 3, 'castle', '#8A6AE8', '#3A2A8A', '#FFE36B', 'stars', 5], ['Nhà nấm hồng', 2, 2, 'hut', '#F2C8E8', '#E5334B', '#8E5CF0', 'stars', 3], ['Học viện phép', 3, 2, 'dome', '#C9A8FF', '#6A4CC0', '#FFE36B', 'stars', 4], ['Hang rồng đá', 3, 2, 'cave', '#6A5A8A', '#3A2A5A', '#FF8A2A', 'stars', 4]],
    p: [['Mèo phù thủy', 'cat', '#2A2A34', '#B48CFF', 'hat', 3], ['Cú pháp thuật', 'owl', '#6A4CC0', '#E8D4FF', 'star', 4], ['Rồng tím nhí', 'lizard', '#8E5CF0', '#FFE36B', 'wings', 5], ['Thỏ tinh linh', 'bunny', '#E8D4FF', '#B48CFF', 'glow', 4], ['Cáo ma thuật', 'fox', '#B48CFF', '#FFFFFF', 'star', 4]] });
})(typeof window !== 'undefined' ? window : this);
