/* EWT Garden — Hộ chiếu văn hoá: thông tin tiếng Anh về từng công trình của 23 khu quốc gia (dùng ở trình duyệt).
   Mỗi khu có 4 điểm chạm (công trình biểu tượng, công trình văn hoá, cờ, vật phẩm). Mỗi điểm: [tên EN, tên VI, câu tiếng Anh (A2), dịch VI, [[từ, nghĩa], …]].
   Câu hỏi mini-quiz (có đáp án) nằm ở máy chủ: garden-culture-quiz.js. Chỉ ghi những điều chắc chắn đúng. */
(function (root) {
  'use strict';
  var C = {
    vietnam: { country: 'Vietnam', vi: 'Việt Nam', spots: {
      onepillar: ['One Pillar Pagoda', 'Chùa Một Cột', 'The One Pillar Pagoda stands on a single stone pillar in a pond in Hanoi. It was built in 1049.', 'Chùa Một Cột đứng trên một cột đá duy nhất giữa hồ ở Hà Nội. Chùa được xây năm 1049.', [['pagoda', 'chùa'], ['pillar', 'cột'], ['pond', 'ao, hồ nhỏ']]],
      hoianhouse: ['Hoi An Ancient Town', 'Phố cổ Hội An', 'Hoi An is famous for its yellow houses and colourful lanterns. It is a UNESCO World Heritage Site.', 'Hội An nổi tiếng với những ngôi nhà vàng và đèn lồng nhiều màu. Đây là Di sản Thế giới của UNESCO.', [['lantern', 'đèn lồng'], ['ancient', 'cổ xưa'], ['heritage', 'di sản']]],
      vnflag: ['The flag of Vietnam', 'Quốc kỳ Việt Nam', 'The flag of Vietnam is red with a yellow star in the middle.', 'Quốc kỳ Việt Nam màu đỏ với ngôi sao vàng ở giữa.', [['flag', 'lá cờ'], ['star', 'ngôi sao'], ['middle', 'ở giữa']]],
      conicalhat: ['Conical hat (nón lá)', 'Nón lá', 'A conical hat is made from palm leaves. It protects people from the sun and the rain.', 'Nón lá được làm từ lá cọ. Nón che nắng và che mưa cho người đội.', [['conical', 'hình nón'], ['palm leaf', 'lá cọ'], ['protect', 'bảo vệ']]] } },
    thailand: { country: 'Thailand', vi: 'Thái Lan', spots: {
      wat: ['Thai temple (wat)', 'Chùa Thái (wat)', 'A Thai temple is called a wat. Many wats have golden towers and colourful roofs.', 'Chùa ở Thái Lan gọi là wat. Nhiều ngôi chùa có tháp vàng và mái nhà nhiều màu.', [['temple', 'ngôi chùa, đền'], ['golden', 'bằng vàng, vàng óng'], ['roof', 'mái nhà']]],
      floatmarket: ['Floating market', 'Chợ nổi', 'At a floating market, people sell fruit and food from small boats.', 'Ở chợ nổi, người ta bán trái cây và đồ ăn trên những chiếc thuyền nhỏ.', [['market', 'chợ'], ['boat', 'thuyền'], ['sell', 'bán']]],
      thflag: ['The flag of Thailand', 'Quốc kỳ Thái Lan', 'The flag of Thailand has five horizontal stripes: red, white, blue, white and red. The blue stripe is in the middle and is the widest.', 'Quốc kỳ Thái Lan có năm sọc ngang: đỏ, trắng, xanh, trắng, đỏ. Sọc xanh ở giữa và rộng nhất.', [['stripe', 'sọc'], ['horizontal', 'nằm ngang'], ['wide', 'rộng']]],
      thelephant: ['The elephant', 'Con voi', 'The elephant is the national animal of Thailand.', 'Voi là quốc thú của Thái Lan.', [['elephant', 'con voi'], ['national', 'thuộc quốc gia'], ['animal', 'động vật']]] } },
    japan: { country: 'Japan', vi: 'Nhật Bản', spots: {
      fuji: ['Mount Fuji', 'Núi Phú Sĩ', 'Mount Fuji is the highest mountain in Japan. It is 3,776 metres tall.', 'Núi Phú Sĩ là ngọn núi cao nhất Nhật Bản. Núi cao 3.776 mét.', [['mountain', 'ngọn núi'], ['highest', 'cao nhất'], ['tall', 'cao']]],
      japancastle: ['Japanese castle', 'Lâu đài Nhật Bản', 'Himeji Castle is a famous white castle in Japan. People call it the White Heron Castle.', 'Lâu đài Himeji là một lâu đài trắng nổi tiếng ở Nhật Bản. Người ta gọi nó là Lâu đài Diệc Trắng.', [['castle', 'lâu đài'], ['heron', 'con diệc'], ['famous', 'nổi tiếng']]],
      jpflag: ['The flag of Japan', 'Quốc kỳ Nhật Bản', 'The flag of Japan is white with a red circle. The circle is the sun.', 'Quốc kỳ Nhật Bản màu trắng với hình tròn đỏ. Hình tròn là mặt trời.', [['circle', 'hình tròn'], ['sun', 'mặt trời'], ['white', 'màu trắng']]],
      maneki: ['Maneki-neko (lucky cat)', 'Mèo may mắn', 'The maneki-neko is a lucky cat. It raises its paw to bring good luck.', 'Maneki-neko là chú mèo may mắn. Mèo giơ chân lên để mang lại vận may.', [['lucky', 'may mắn'], ['paw', 'bàn chân thú'], ['raise', 'giơ lên']]] } },
    china: { country: 'China', vi: 'Trung Quốc', spots: {
      greatwall: ['The Great Wall', 'Vạn Lý Trường Thành', 'The Great Wall of China is more than 20,000 kilometres long. People built it to protect the country.', 'Vạn Lý Trường Thành dài hơn 20.000 km. Người ta xây nó để bảo vệ đất nước.', [['wall', 'bức tường'], ['protect', 'bảo vệ'], ['kilometre', 'ki-lô-mét']]],
      chinapagoda: ['Chinese pagoda', 'Tháp chùa Trung Quốc', 'A pagoda is a tall tower with many roofs. It is often part of a temple.', 'Pagoda là toà tháp cao có nhiều tầng mái. Nó thường là một phần của ngôi chùa.', [['pagoda', 'tháp chùa'], ['tower', 'toà tháp'], ['roof', 'mái nhà']]],
      cnflag: ['The flag of China', 'Quốc kỳ Trung Quốc', 'The flag of China is red with five yellow stars. One star is big and four stars are small.', 'Quốc kỳ Trung Quốc màu đỏ với năm ngôi sao vàng. Một sao lớn và bốn sao nhỏ.', [['star', 'ngôi sao'], ['yellow', 'màu vàng'], ['small', 'nhỏ']]],
      cnlantern: ['Red lantern', 'Đèn lồng đỏ', 'People hang red lanterns during Chinese New Year. Red is a lucky colour in China.', 'Người ta treo đèn lồng đỏ trong dịp Tết Trung Quốc. Màu đỏ là màu may mắn ở Trung Quốc.', [['lantern', 'đèn lồng'], ['hang', 'treo'], ['lucky', 'may mắn']]] } },
    india: { country: 'India', vi: 'Ấn Độ', spots: {
      tajmahal: ['The Taj Mahal', 'Đền Taj Mahal', 'The Taj Mahal is in the city of Agra. A king built it for his wife, Mumtaz Mahal.', 'Taj Mahal ở thành phố Agra. Một vị vua xây nó cho vợ mình, Mumtaz Mahal.', [['king', 'vua'], ['wife', 'vợ'], ['dome', 'mái vòm']]],
      tuktuk: ['Tuk-tuk', 'Xe tuk-tuk', 'A tuk-tuk is a small three-wheeled taxi. It is popular in India and Thailand.', 'Tuk-tuk là loại taxi nhỏ ba bánh. Nó phổ biến ở Ấn Độ và Thái Lan.', [['wheel', 'bánh xe'], ['taxi', 'xe taxi'], ['popular', 'phổ biến']]],
      inflag: ['The flag of India', 'Quốc kỳ Ấn Độ', 'The flag of India has three colours: orange, white and green. A blue wheel is in the middle.', 'Quốc kỳ Ấn Độ có ba màu: cam, trắng và xanh lá. Giữa cờ có một bánh xe màu xanh dương.', [['wheel', 'bánh xe'], ['orange', 'màu cam'], ['green', 'xanh lá']]],
      diya: ['Diya lamp', 'Đèn dầu diya', 'A diya is a small oil lamp. People light diyas at the festival of Diwali.', 'Diya là chiếc đèn dầu nhỏ. Người ta thắp diya trong lễ hội Diwali.', [['lamp', 'cái đèn'], ['light', 'thắp sáng'], ['festival', 'lễ hội']]] } },
    indonesia: { country: 'Indonesia', vi: 'Indonesia', spots: {
      borobudur: ['Borobudur Temple', 'Đền Borobudur', 'Borobudur is the largest Buddhist temple in the world. It is on the island of Java.', 'Borobudur là ngôi đền Phật giáo lớn nhất thế giới. Nó nằm trên đảo Java.', [['temple', 'ngôi đền'], ['largest', 'lớn nhất'], ['island', 'hòn đảo']]],
      baligate: ['Balinese split gate', 'Cổng chẻ Bali', 'A split gate looks like a tower cut into two halves. You can see it at temples in Bali.', 'Cổng chẻ trông như một tháp bị cắt làm đôi. Bạn có thể thấy nó ở các đền thờ ở Bali.', [['gate', 'cổng'], ['half', 'một nửa'], ['tower', 'toà tháp']]],
      idflag: ['The flag of Indonesia', 'Quốc kỳ Indonesia', 'The flag of Indonesia has two stripes. The top is red and the bottom is white.', 'Quốc kỳ Indonesia có hai sọc. Sọc trên màu đỏ và sọc dưới màu trắng.', [['top', 'phía trên'], ['bottom', 'phía dưới'], ['stripe', 'sọc']]],
      wayang: ['Wayang puppet', 'Rối bóng wayang', 'Wayang is a traditional puppet show. The puppets make shadows on a white screen.', 'Wayang là nghệ thuật múa rối truyền thống. Những con rối tạo bóng trên màn trắng.', [['puppet', 'con rối'], ['shadow', 'cái bóng'], ['traditional', 'truyền thống']]] } },
    france: { country: 'France', vi: 'Pháp', spots: {
      eiffel: ['The Eiffel Tower', 'Tháp Eiffel', 'The Eiffel Tower is in Paris. It was built in 1889 for a big world fair.', 'Tháp Eiffel ở Paris. Tháp được xây năm 1889 cho một hội chợ thế giới lớn.', [['tower', 'toà tháp'], ['build', 'xây dựng'], ['fair', 'hội chợ']]],
      cafe: ['French café', 'Quán cà phê Pháp', 'In France, many people drink coffee and eat a croissant at a café.', 'Ở Pháp, nhiều người uống cà phê và ăn bánh sừng bò ở quán cà phê.', [['café', 'quán cà phê'], ['croissant', 'bánh sừng bò'], ['coffee', 'cà phê']]],
      frflag: ['The flag of France', 'Quốc kỳ Pháp', 'The flag of France has three vertical stripes: blue, white and red.', 'Quốc kỳ Pháp có ba sọc dọc: xanh dương, trắng và đỏ.', [['vertical', 'thẳng đứng'], ['blue', 'xanh dương'], ['stripe', 'sọc']]],
      baguette: ['Baguette', 'Bánh mì baguette', 'A baguette is a long, thin French bread. It is crispy outside and soft inside.', 'Baguette là loại bánh mì Pháp dài và mỏng. Vỏ giòn bên ngoài và ruột mềm bên trong.', [['bread', 'bánh mì'], ['crispy', 'giòn'], ['soft', 'mềm']]] } },
    italy: { country: 'Italy', vi: 'Ý', spots: {
      colosseum: ['The Colosseum', 'Đấu trường Colosseum', 'The Colosseum is in Rome. In ancient times, people watched gladiator fights there.', 'Colosseum ở Rome. Thời cổ đại, người ta xem các trận đấu của đấu sĩ ở đó.', [['ancient', 'cổ xưa'], ['gladiator', 'đấu sĩ'], ['fight', 'trận đấu, cuộc chiến']]],
      pizzeria: ['Pizzeria', 'Tiệm pizza', 'A pizzeria is a restaurant that makes pizza in a very hot oven.', 'Pizzeria là nhà hàng làm pizza trong lò rất nóng.', [['oven', 'lò nướng'], ['restaurant', 'nhà hàng'], ['dough', 'bột nhào']]],
      itflag: ['The flag of Italy', 'Quốc kỳ Ý', 'The flag of Italy is green, white and red. The stripes are vertical.', 'Quốc kỳ Ý gồm xanh lá, trắng và đỏ. Các sọc thẳng đứng.', [['green', 'xanh lá'], ['vertical', 'thẳng đứng'], ['stripe', 'sọc']]],
      pizza: ['Pizza', 'Bánh pizza', 'Pizza comes from Naples, a city in Italy. A classic pizza has tomato and cheese.', 'Pizza bắt nguồn từ Naples, một thành phố ở Ý. Pizza truyền thống có cà chua và phô mai.', [['cheese', 'phô mai'], ['tomato', 'cà chua'], ['slice', 'miếng, lát']]] } },
    netherlands: { country: 'the Netherlands', vi: 'Hà Lan', spots: {
      dutchwindmill: ['Dutch windmill', 'Cối xay gió Hà Lan', 'A windmill uses the wind to turn its big blades. In the Netherlands, windmills helped pump water from the land.', 'Cối xay gió dùng gió để quay những cánh lớn. Ở Hà Lan, cối xay gió giúp bơm nước khỏi đất.', [['blade', 'cánh quạt'], ['pump', 'bơm'], ['wind', 'gió']]],
      tulipfield: ['Tulip field', 'Cánh đồng tulip', 'In spring, the Netherlands has colourful tulip fields. The tulip is a famous Dutch flower.', 'Mùa xuân, Hà Lan có những cánh đồng tulip rực rỡ. Hoa tulip là loài hoa nổi tiếng của Hà Lan.', [['tulip', 'hoa tulip'], ['spring', 'mùa xuân'], ['field', 'cánh đồng']]],
      nlflag: ['The flag of the Netherlands', 'Quốc kỳ Hà Lan', 'The flag of the Netherlands has three horizontal stripes: red, white and blue.', 'Quốc kỳ Hà Lan có ba sọc ngang: đỏ, trắng và xanh dương.', [['horizontal', 'nằm ngang'], ['red', 'màu đỏ'], ['blue', 'xanh dương']]],
      woodenshoe: ['Wooden shoes (klompen)', 'Guốc gỗ (klompen)', 'Wooden shoes are called klompen in Dutch. Farmers wore them to keep their feet dry.', 'Giày gỗ tiếng Hà Lan gọi là klompen. Nông dân đi chúng để giữ cho chân khô ráo.', [['wooden', 'bằng gỗ'], ['farmer', 'nông dân'], ['dry', 'khô']]] } },
    uk: { country: 'the United Kingdom', vi: 'Vương quốc Anh', spots: {
      bigben: ['Big Ben', 'Tháp Big Ben', 'Big Ben is the nickname of the great bell in the clock tower in London.', 'Big Ben là biệt danh của chiếc chuông lớn trong tháp đồng hồ ở London.', [['bell', 'cái chuông'], ['clock', 'đồng hồ'], ['nickname', 'biệt danh']]],
      doubledecker: ['Double-decker bus', 'Xe buýt hai tầng', 'A double-decker bus has two floors. Red buses are a symbol of London.', 'Xe buýt hai tầng có hai tầng. Xe buýt đỏ là biểu tượng của London.', [['floor', 'tầng'], ['symbol', 'biểu tượng'], ['bus', 'xe buýt']]],
      ukflag: ['The Union Jack', 'Cờ Union Jack', 'The Union Jack is the flag of the United Kingdom. It joins the crosses of England, Scotland and Ireland.', 'Union Jack là quốc kỳ của Vương quốc Anh. Nó kết hợp các chữ thập của Anh, Scotland và Ireland.', [['cross', 'chữ thập'], ['join', 'kết hợp'], ['flag', 'lá cờ']]],
      phonebox: ['Red telephone box', 'Hộp điện thoại đỏ', 'Red telephone boxes are a famous sight in the UK. People used them to make phone calls in the street.', 'Hộp điện thoại đỏ là hình ảnh nổi tiếng ở Anh. Người ta dùng chúng để gọi điện ngoài phố.', [['telephone', 'điện thoại'], ['sight', 'cảnh tượng'], ['street', 'đường phố']]] } },
    germany: { country: 'Germany', vi: 'Đức', spots: {
      brandenburg: ['Brandenburg Gate', 'Cổng Brandenburg', 'The Brandenburg Gate is a famous monument in Berlin. It is a symbol of peace and unity.', 'Cổng Brandenburg là công trình nổi tiếng ở Berlin. Nó là biểu tượng của hoà bình và thống nhất.', [['gate', 'cổng'], ['monument', 'đài kỷ niệm'], ['unity', 'sự thống nhất']]],
      bavarianhouse: ['Half-timbered house', 'Nhà khung gỗ', 'Many old German houses have wooden beams in their walls. We call them half-timbered houses.', 'Nhiều ngôi nhà cổ ở Đức có xà gỗ trong tường. Ta gọi đó là nhà khung gỗ.', [['beam', 'xà gỗ'], ['wooden', 'bằng gỗ'], ['wall', 'bức tường']]],
      deflag: ['The flag of Germany', 'Quốc kỳ Đức', 'The flag of Germany has three horizontal stripes: black, red and gold.', 'Quốc kỳ Đức có ba sọc ngang: đen, đỏ và vàng.', [['black', 'màu đen'], ['gold', 'màu vàng kim'], ['stripe', 'sọc']]],
      pretzel: ['Pretzel', 'Bánh pretzel', 'A pretzel is a baked bread in a twisted shape. It is popular in Germany.', 'Pretzel là loại bánh mì nướng có hình xoắn. Nó phổ biến ở Đức.', [['twisted', 'xoắn'], ['baked', 'được nướng'], ['shape', 'hình dạng']]] } },
    usa: { country: 'the United States', vi: 'Hoa Kỳ', spots: {
      liberty: ['Statue of Liberty', 'Tượng Nữ thần Tự do', 'France gave the Statue of Liberty to the United States. It stands in New York Harbor.', 'Nước Pháp tặng Tượng Nữ thần Tự do cho Hoa Kỳ. Tượng đứng ở cảng New York.', [['statue', 'bức tượng'], ['liberty', 'tự do'], ['harbor', 'bến cảng']]],
      yellowcab: ['Yellow taxi', 'Taxi vàng', 'Yellow taxis are a symbol of New York City.', 'Taxi vàng là biểu tượng của thành phố New York.', [['taxi', 'xe taxi'], ['symbol', 'biểu tượng'], ['city', 'thành phố']]],
      usflag: ['The flag of the USA', 'Quốc kỳ Hoa Kỳ', 'The flag of the United States has 50 stars and 13 stripes. The stars are for the states, and the stripes are for the first colonies.', 'Quốc kỳ Hoa Kỳ có 50 ngôi sao và 13 sọc. Các sao tượng trưng cho các bang, các sọc tượng trưng cho các thuộc địa đầu tiên.', [['state', 'bang'], ['stripe', 'sọc'], ['colony', 'thuộc địa']]],
      hotdog: ['Hot dog', 'Bánh mì xúc xích', 'A hot dog is a sausage in a soft bun. It is a popular fast food in the USA.', 'Hot dog là xúc xích kẹp trong bánh mì mềm. Đây là món ăn nhanh phổ biến ở Mỹ.', [['sausage', 'xúc xích'], ['bun', 'bánh mì tròn'], ['fast food', 'đồ ăn nhanh']]] } },
    greece: { country: 'Greece', vi: 'Hy Lạp', spots: {
      parthenon: ['The Parthenon', 'Đền Parthenon', 'The Parthenon is an ancient temple on the Acropolis in Athens. It was built for the goddess Athena.', 'Parthenon là ngôi đền cổ trên đồi Acropolis ở Athens. Nó được xây cho nữ thần Athena.', [['temple', 'ngôi đền'], ['goddess', 'nữ thần'], ['ancient', 'cổ xưa']]],
      santorini: ['Santorini', 'Đảo Santorini', 'Santorini is a Greek island. It is famous for its white houses with blue domes.', 'Santorini là một hòn đảo của Hy Lạp. Đảo nổi tiếng với những ngôi nhà trắng có mái vòm xanh.', [['island', 'hòn đảo'], ['dome', 'mái vòm'], ['famous', 'nổi tiếng']]],
      grflag: ['The flag of Greece', 'Quốc kỳ Hy Lạp', 'The flag of Greece has blue and white stripes and a white cross in the corner.', 'Quốc kỳ Hy Lạp có các sọc xanh và trắng cùng một chữ thập trắng ở góc.', [['corner', 'góc'], ['cross', 'chữ thập'], ['stripe', 'sọc']]],
      amphora: ['Amphora', 'Bình amphora', 'An amphora is a tall clay jar. In ancient Greece, people used it to store oil and wine.', 'Amphora là chiếc bình đất sét cao. Ở Hy Lạp cổ đại, người ta dùng nó để chứa dầu và rượu vang.', [['clay', 'đất sét'], ['jar', 'cái bình'], ['store', 'cất giữ']]] } },
    sweden: { country: 'Sweden', vi: 'Thụy Điển', spots: {
      redcottage: ['Red wooden house', 'Nhà gỗ đỏ', 'Many Swedish houses are painted red with white corners. The red colour is called Falu red.', 'Nhiều ngôi nhà ở Thụy Điển được sơn đỏ với góc trắng. Màu đỏ đó gọi là đỏ Falu.', [['cottage', 'nhà nhỏ ở nông thôn'], ['paint', 'sơn'], ['corner', 'góc']]],
      dalahorse: ['Dala horse', 'Ngựa Dala', 'The Dala horse is a small wooden horse from Sweden. It is painted red with colourful patterns.', 'Ngựa Dala là con ngựa gỗ nhỏ của Thụy Điển. Nó được sơn đỏ với hoa văn nhiều màu.', [['wooden', 'bằng gỗ'], ['pattern', 'hoa văn'], ['painted', 'được sơn']]],
      seflag: ['The flag of Sweden', 'Quốc kỳ Thụy Điển', 'The flag of Sweden is blue with a yellow cross.', 'Quốc kỳ Thụy Điển màu xanh dương với chữ thập vàng.', [['cross', 'chữ thập'], ['yellow', 'màu vàng'], ['blue', 'xanh dương']]],
      cinnamonbun: ['Cinnamon bun', 'Bánh quế cinnamon', 'A cinnamon bun is a sweet roll with cinnamon. Swedes eat it with coffee during fika, a coffee break.', 'Bánh cuộn quế là loại bánh ngọt có quế. Người Thụy Điển ăn nó với cà phê trong giờ fika, giờ nghỉ uống cà phê.', [['cinnamon', 'quế'], ['sweet', 'ngọt'], ['roll', 'bánh cuộn']]] } },
    switzerland: { country: 'Switzerland', vi: 'Thụy Sĩ', spots: {
      matterhorn: ['The Matterhorn', 'Đỉnh Matterhorn', 'The Matterhorn is a famous mountain in the Alps. It is on the border between Switzerland and Italy.', 'Matterhorn là ngọn núi nổi tiếng trong dãy Alps. Núi nằm ở biên giới giữa Thụy Sĩ và Ý.', [['border', 'biên giới'], ['peak', 'đỉnh núi'], ['mountain', 'ngọn núi']]],
      swisschalet: ['Swiss chalet', 'Nhà gỗ chalet', 'A chalet is a wooden house in the mountains. It often has a wide roof and flower boxes.', 'Chalet là ngôi nhà gỗ trên núi. Nhà thường có mái rộng và những chậu hoa.', [['chalet', 'nhà gỗ miền núi'], ['wide', 'rộng'], ['roof', 'mái nhà']]],
      chflag: ['The flag of Switzerland', 'Quốc kỳ Thụy Sĩ', 'The flag of Switzerland is red with a white cross. It is square.', 'Quốc kỳ Thụy Sĩ màu đỏ với chữ thập trắng. Lá cờ có hình vuông.', [['square', 'hình vuông'], ['cross', 'chữ thập'], ['red', 'màu đỏ']]],
      cuckooclock: ['Cuckoo clock', 'Đồng hồ cúc cu', 'A cuckoo clock has a small bird that comes out and sings every hour.', 'Đồng hồ cúc cu có một chú chim nhỏ chui ra và hót mỗi giờ.', [['cuckoo', 'chim cúc cu'], ['hour', 'giờ'], ['sing', 'hót, hát']]] } },
    korea: { country: 'South Korea', vi: 'Hàn Quốc', spots: {
      gyeongbok: ['Gyeongbokgung Palace', 'Cung Gyeongbokgung', 'Gyeongbokgung is a big royal palace in Seoul. It was built in 1395.', 'Gyeongbokgung là một cung điện hoàng gia lớn ở Seoul. Cung được xây năm 1395.', [['palace', 'cung điện'], ['royal', 'thuộc hoàng gia'], ['built', 'được xây']]],
      hanok: ['Hanok', 'Nhà hanok', 'A hanok is a traditional Korean house. It has a curved tile roof and a warm floor.', 'Hanok là ngôi nhà truyền thống của Hàn Quốc. Nhà có mái ngói cong và sàn ấm.', [['traditional', 'truyền thống'], ['curved', 'cong'], ['tile', 'ngói']]],
      krflag: ['The flag of South Korea', 'Quốc kỳ Hàn Quốc', 'The flag of South Korea is white with a red and blue circle in the middle. It also has four black signs in the corners.', 'Quốc kỳ Hàn Quốc màu trắng, có hình tròn đỏ và xanh ở giữa. Lá cờ còn có bốn ký hiệu đen ở các góc.', [['circle', 'hình tròn'], ['corner', 'góc'], ['black', 'màu đen']]],
      kimchijar: ['Kimchi', 'Kim chi', 'Kimchi is a popular Korean food. It is made from vegetables like cabbage, and people keep it in big jars.', 'Kim chi là món ăn nổi tiếng của Hàn Quốc. Món được làm từ rau như cải thảo, và người ta cất trong những chum lớn.', [['cabbage', 'cải thảo'], ['jar', 'chum, hũ'], ['vegetable', 'rau củ']]] } },
    turkey: { country: 'Turkey', vi: 'Thổ Nhĩ Kỳ', spots: {
      hagiasophia: ['Hagia Sophia', 'Thánh đường Hagia Sophia', 'Hagia Sophia is a famous building in Istanbul. It has a huge dome and is about 1,500 years old.', 'Hagia Sophia là toà nhà nổi tiếng ở Istanbul. Nơi này có mái vòm khổng lồ và khoảng 1.500 năm tuổi.', [['dome', 'mái vòm'], ['huge', 'khổng lồ'], ['famous', 'nổi tiếng']]],
      cappadocia: ['Cappadocia', 'Cappadocia', 'In Cappadocia, tourists can ride in hot air balloons. They fly over tall rock towers called fairy chimneys.', 'Ở Cappadocia, du khách có thể đi khinh khí cầu. Họ bay trên những tháp đá cao gọi là "ống khói của các nàng tiên".', [['balloon', 'khinh khí cầu'], ['tourist', 'du khách'], ['tower', 'tháp']]],
      trflag: ['The flag of Turkey', 'Quốc kỳ Thổ Nhĩ Kỳ', 'The flag of Turkey is red with a white crescent moon and a white star.', 'Quốc kỳ Thổ Nhĩ Kỳ màu đỏ với trăng lưỡi liềm trắng và một ngôi sao trắng.', [['crescent', 'lưỡi liềm'], ['moon', 'mặt trăng'], ['star', 'ngôi sao']]],
      turkishtea: ['Turkish tea', 'Trà Thổ Nhĩ Kỳ', 'People in Turkey drink tea in small glasses. The glasses are shaped like tulips.', 'Người Thổ Nhĩ Kỳ uống trà trong những chiếc ly nhỏ. Ly có hình dáng giống bông hoa tulip.', [['glass', 'ly, cốc'], ['shape', 'hình dáng'], ['tulip', 'hoa tulip']]] } },
    australia: { country: 'Australia', vi: 'Úc', spots: {
      sydneyopera: ['Sydney Opera House', 'Nhà hát Opera Sydney', 'The Sydney Opera House is next to the sea. Its roof looks like white sails.', 'Nhà hát Opera Sydney nằm cạnh biển. Mái nhà trông như những cánh buồm trắng.', [['roof', 'mái nhà'], ['sail', 'cánh buồm'], ['opera', 'nhạc kịch']]],
      outbackhouse: ['The Outback', 'Vùng Outback', 'The Outback is a large, dry area in the middle of Australia. Houses there often have a veranda for shade.', 'Outback là vùng đất rộng và khô ở giữa nước Úc. Nhà ở đó thường có hiên để che nắng.', [['dry', 'khô'], ['area', 'khu vực'], ['shade', 'bóng râm']]],
      auflag: ['The flag of Australia', 'Quốc kỳ Úc', 'The flag of Australia is dark blue. It has the Union Jack in the corner and white stars.', 'Quốc kỳ Úc màu xanh đậm. Lá cờ có hình Union Jack ở góc và các ngôi sao trắng.', [['corner', 'góc'], ['dark blue', 'xanh đậm'], ['stars', 'những ngôi sao']]],
      boomerang: ['Boomerang', 'Bumerang', 'A boomerang is a curved piece of wood. Some boomerangs come back when you throw them.', 'Bumerang là một mảnh gỗ cong. Một số bumerang bay quay trở lại khi bạn ném.', [['curved', 'cong'], ['throw', 'ném'], ['wood', 'gỗ']]] } },
    canada: { country: 'Canada', vi: 'Canada', spots: {
      cntower: ['CN Tower', 'Tháp CN', 'The CN Tower is a very tall tower in Toronto. People can see the city from its top.', 'Tháp CN là toà tháp rất cao ở Toronto. Từ trên đỉnh, mọi người có thể ngắm cả thành phố.', [['tower', 'toà tháp'], ['tall', 'cao'], ['city', 'thành phố']]],
      logcabin: ['Log cabin', 'Nhà gỗ rừng', 'A log cabin is a small house made of logs. Many people in Canada stay in cabins near forests and lakes.', 'Nhà gỗ rừng là ngôi nhà nhỏ làm bằng các khúc gỗ. Nhiều người Canada ở trong nhà gỗ gần rừng và hồ.', [['log', 'khúc gỗ'], ['cabin', 'nhà gỗ nhỏ'], ['forest', 'rừng']]],
      caflag: ['The flag of Canada', 'Quốc kỳ Canada', 'The flag of Canada is red and white. It has a red maple leaf in the middle.', 'Quốc kỳ Canada màu đỏ và trắng. Lá cờ có một chiếc lá phong đỏ ở giữa.', [['maple leaf', 'lá phong'], ['white', 'màu trắng'], ['middle', 'ở giữa']]],
      maplesyrup: ['Maple syrup', 'Xi-rô phong', 'Maple syrup is a sweet liquid made from maple trees. Canadians often eat it on pancakes.', 'Xi-rô phong là chất lỏng ngọt làm từ cây phong. Người Canada thường ăn nó với bánh kếp.', [['syrup', 'xi-rô'], ['sweet', 'ngọt'], ['pancake', 'bánh kếp']]] } },
    mexico: { country: 'Mexico', vi: 'Mexico', spots: {
      chichen: ['Chichén Itzá', 'Chichén Itzá', 'Chichén Itzá is an ancient city built by the Maya. Its big pyramid is called El Castillo.', 'Chichén Itzá là thành phố cổ do người Maya xây dựng. Kim tự tháp lớn của nơi này có tên El Castillo.', [['ancient', 'cổ xưa'], ['pyramid', 'kim tự tháp'], ['built', 'đã xây']]],
      hacienda: ['Hacienda', 'Nhà hacienda', 'A hacienda is a large house or farm in Mexico. Many haciendas have bright colours and flower pots.', 'Hacienda là ngôi nhà hoặc trang trại lớn ở Mexico. Nhiều hacienda có màu sắc tươi sáng và chậu hoa.', [['large', 'lớn'], ['bright', 'tươi sáng'], ['flower pot', 'chậu hoa']]],
      sombrero: ['Sombrero', 'Mũ sombrero', 'A sombrero is a hat with a very wide edge. It keeps the sun off your face.', 'Sombrero là loại mũ có vành rất rộng. Mũ che nắng cho khuôn mặt bạn.', [['hat', 'mũ'], ['wide', 'rộng'], ['sun', 'mặt trời, nắng']]],
      pinata: ['Piñata', 'Piñata', 'A piñata is a colourful paper toy filled with sweets. Children hit it with a stick at parties.', 'Piñata là món đồ chơi giấy nhiều màu chứa đầy kẹo. Trẻ em dùng gậy đập nó trong các bữa tiệc.', [['toy', 'đồ chơi'], ['stick', 'cái gậy'], ['party', 'bữa tiệc']]] } },
    brazil: { country: 'Brazil', vi: 'Brazil', spots: {
      christredeemer: ['Christ the Redeemer', 'Tượng Chúa Cứu Thế', 'Christ the Redeemer is a big statue on a mountain in Rio de Janeiro. Its arms are open wide.', 'Tượng Chúa Cứu Thế là bức tượng lớn trên ngọn núi ở Rio de Janeiro. Hai cánh tay tượng dang rộng.', [['statue', 'bức tượng'], ['mountain', 'ngọn núi'], ['arm', 'cánh tay']]],
      carnival: ['Carnival', 'Lễ hội Carnival', 'Carnival is a big festival in Brazil. People dance, play music and wear colourful costumes.', 'Carnival là lễ hội lớn ở Brazil. Mọi người nhảy múa, chơi nhạc và mặc trang phục nhiều màu.', [['festival', 'lễ hội'], ['costume', 'trang phục'], ['dance', 'nhảy múa']]],
      toucanpost: ['Toucan', 'Chim toucan', 'A toucan is a bird with a very big, colourful beak. It lives in the rainforests of South America.', 'Toucan là loài chim có chiếc mỏ rất to và nhiều màu. Chim sống trong rừng mưa ở Nam Mỹ.', [['beak', 'cái mỏ'], ['rainforest', 'rừng mưa nhiệt đới'], ['bird', 'con chim']]],
      braball: ['Football in Brazil', 'Bóng đá ở Brazil', 'Football is very popular in Brazil. The Brazilian team has won the World Cup many times.', 'Bóng đá rất được yêu thích ở Brazil. Đội tuyển Brazil đã nhiều lần vô địch World Cup.', [['popular', 'được yêu thích'], ['team', 'đội'], ['won', 'đã thắng']]] } },
    egypt: { country: 'Egypt', vi: 'Ai Cập', spots: {
      giza: ['The Pyramids of Giza', 'Kim tự tháp Giza', 'The Pyramids of Giza are huge stone tombs. They are about 4,500 years old.', 'Các kim tự tháp Giza là những ngôi mộ đá khổng lồ. Chúng khoảng 4.500 năm tuổi.', [['tomb', 'ngôi mộ'], ['stone', 'đá'], ['huge', 'khổng lồ']]],
      karnak: ['Karnak Temple', 'Đền Karnak', 'Karnak is a huge temple in Luxor. It has tall stone columns with pictures carved on them.', 'Karnak là ngôi đền khổng lồ ở Luxor. Đền có những cột đá cao khắc đầy hình ảnh.', [['temple', 'ngôi đền'], ['column', 'cột'], ['carved', 'được khắc']]],
      ankh: ['The ankh', 'Biểu tượng Ankh', 'The ankh is an ancient Egyptian symbol. It means "life".', 'Ankh là biểu tượng của Ai Cập cổ đại. Nó có nghĩa là "sự sống".', [['symbol', 'biểu tượng'], ['ancient', 'cổ đại'], ['life', 'sự sống']]],
      scarab: ['The scarab', 'Bọ hung Scarab', 'The scarab is a kind of beetle. Ancient Egyptians thought it was a sign of good luck.', 'Scarab là một loài bọ cánh cứng. Người Ai Cập cổ đại cho rằng nó là dấu hiệu may mắn.', [['beetle', 'bọ cánh cứng'], ['sign', 'dấu hiệu'], ['luck', 'may mắn']]] } },
    morocco: { country: 'Morocco', vi: 'Ma-rốc', spots: {
      koutoubia: ['Koutoubia Mosque', 'Nhà thờ Koutoubia', 'The Koutoubia Mosque is in Marrakech. Its tall tower can be seen from far away.', 'Nhà thờ Hồi giáo Koutoubia ở Marrakech. Toà tháp cao của nó có thể nhìn thấy từ rất xa.', [['mosque', 'nhà thờ Hồi giáo'], ['tower', 'toà tháp'], ['far', 'xa']]],
      riad: ['Riad', 'Nhà riad', 'A riad is a traditional house with a garden or a fountain in the middle. The courtyard is open to the sky.', 'Riad là ngôi nhà truyền thống có khu vườn hoặc đài phun nước ở giữa. Sân trong mở ra bầu trời.', [['courtyard', 'sân trong'], ['fountain', 'đài phun nước'], ['traditional', 'truyền thống']]],
      maflag: ['The flag of Morocco', 'Quốc kỳ Ma-rốc', 'The flag of Morocco is red with a green star in the middle.', 'Quốc kỳ Ma-rốc màu đỏ với ngôi sao xanh lá ở giữa.', [['green', 'xanh lá'], ['star', 'ngôi sao'], ['red', 'màu đỏ']]],
      moroccanteapot: ['Moroccan mint tea', 'Trà bạc hà Ma-rốc', 'Moroccan mint tea is a sweet drink. People pour it into small glasses from a high teapot.', 'Trà bạc hà Ma-rốc là thức uống ngọt. Người ta rót trà vào ly nhỏ từ ấm trà đưa cao.', [['pour', 'rót'], ['mint', 'bạc hà'], ['teapot', 'ấm trà']]] } },
    spain: { country: 'Spain', vi: 'Tây Ban Nha', spots: {
      sagrada: ['Sagrada Família', 'Nhà thờ Sagrada Família', 'The Sagrada Família is a very tall church in Barcelona. People have been building it for more than one hundred years.', 'Sagrada Família là nhà thờ rất cao ở Barcelona. Người ta đã xây nó hơn một trăm năm.', [['church', 'nhà thờ'], ['tall', 'cao'], ['build', 'xây dựng']]],
      pueblo: ['A white village', 'Làng trắng', 'Many villages in southern Spain have white houses. The white walls keep the houses cool in summer.', 'Nhiều ngôi làng ở miền nam Tây Ban Nha có nhà trắng. Tường trắng giữ cho nhà mát vào mùa hè.', [['village', 'làng'], ['wall', 'bức tường'], ['cool', 'mát']]],
      flamencofan: ['The flamenco fan', 'Quạt flamenco', 'A fan is part of the flamenco dance. Dancers open it and move it in the air.', 'Chiếc quạt là một phần của điệu múa flamenco. Vũ công mở quạt và đưa nó trong không khí.', [['dancer', 'vũ công'], ['fan', 'quạt'], ['move', 'di chuyển']]],
      paellapan: ['Paella', 'Món paella', 'Paella is a rice dish from Spain. It is cooked in a big, flat pan.', 'Paella là món cơm của Tây Ban Nha. Nó được nấu trong một chiếc chảo to và phẳng.', [['rice', 'cơm, gạo'], ['pan', 'chảo'], ['dish', 'món ăn']]] } },
    russia: { country: 'Russia', vi: 'Nga', spots: {
      stbasil: ['Saint Basil\'s Cathedral', 'Nhà thờ Thánh Basil', 'Saint Basil\'s Cathedral is in Moscow. It has colourful domes that look like onions.', 'Nhà thờ Thánh Basil ở Moscow. Nó có những mái vòm nhiều màu trông như củ hành.', [['dome', 'mái vòm'], ['colourful', 'nhiều màu'], ['onion', 'củ hành']]],
      izba: ['An izba', 'Nhà gỗ izba', 'An izba is a traditional Russian wooden house. Its windows often have beautiful carved frames.', 'Izba là ngôi nhà gỗ truyền thống của Nga. Cửa sổ thường có khung chạm khắc rất đẹp.', [['wooden', 'bằng gỗ'], ['carved', 'chạm khắc'], ['frame', 'khung']]],
      ruflag: ['The flag of Russia', 'Quốc kỳ Nga', 'The flag of Russia has three stripes: white, blue and red.', 'Quốc kỳ Nga có ba sọc: trắng, xanh dương và đỏ.', [['stripe', 'sọc'], ['blue', 'xanh dương'], ['white', 'màu trắng']]],
      matryoshka: ['Matryoshka dolls', 'Búp bê matryoshka', 'A matryoshka is a wooden doll. Inside it, there are smaller dolls.', 'Matryoshka là búp bê gỗ. Bên trong nó có những con búp bê nhỏ hơn.', [['doll', 'búp bê'], ['inside', 'bên trong'], ['smaller', 'nhỏ hơn']]] } },
    ireland: { country: 'Ireland', vi: 'Ai-len', spots: {
      moher: ['The Cliffs of Moher', 'Vách đá Moher', 'The Cliffs of Moher are tall cliffs by the sea in Ireland. Many birds live on them.', 'Vách đá Moher là những vách đá cao bên bờ biển ở Ai-len. Nhiều loài chim sống trên đó.', [['cliff', 'vách đá'], ['sea', 'biển'], ['bird', 'chim']]],
      irishcottage: ['An Irish cottage', 'Nhà tranh Ai-len', 'Old Irish cottages are small, white houses. Some have a roof made of straw.', 'Những ngôi nhà tranh Ai-len xưa là nhà nhỏ màu trắng. Có nhà lợp mái bằng rơm.', [['cottage', 'nhà tranh'], ['straw', 'rơm'], ['roof', 'mái nhà']]],
      ieflag: ['The flag of Ireland', 'Quốc kỳ Ai-len', 'The flag of Ireland has three colours: green, white and orange.', 'Quốc kỳ Ai-len có ba màu: xanh lá, trắng và cam.', [['green', 'xanh lá'], ['white', 'màu trắng'], ['orange', 'màu cam']]],
      celticharp: ['The Irish harp', 'Đàn hạc Ai-len', 'The harp is a symbol of Ireland. It has many strings, and you play it with your fingers.', 'Đàn hạc là biểu tượng của Ai-len. Nó có nhiều dây và bạn chơi bằng các ngón tay.', [['symbol', 'biểu tượng'], ['string', 'dây đàn'], ['finger', 'ngón tay']]] } },
    norway: { country: 'Norway', vi: 'Na Uy', spots: {
      stavechurch: ['A stave church', 'Nhà thờ gỗ stave', 'A stave church is an old wooden church in Norway. It has a steep roof with many layers.', 'Nhà thờ stave là nhà thờ gỗ cổ ở Na Uy. Nó có mái dốc nhiều tầng.', [['wooden', 'bằng gỗ'], ['steep', 'dốc'], ['layer', 'tầng, lớp']]],
      rorbu: ['A rorbu', 'Nhà rorbu', 'A rorbu is a small red cabin for fishermen. It stands next to the sea.', 'Rorbu là căn nhà gỗ nhỏ màu đỏ cho ngư dân. Nó nằm ngay cạnh biển.', [['fisherman', 'ngư dân'], ['cabin', 'nhà gỗ nhỏ'], ['sea', 'biển']]],
      noflag: ['The flag of Norway', 'Quốc kỳ Na Uy', 'The flag of Norway is red with a blue and white cross.', 'Quốc kỳ Na Uy màu đỏ với chữ thập xanh dương và trắng.', [['cross', 'chữ thập'], ['blue', 'xanh dương'], ['red', 'màu đỏ']]],
      vikingship: ['A Viking ship', 'Thuyền Viking', 'The Vikings sailed in long wooden ships. Their ships had a big square sail.', 'Người Viking đi biển bằng những con thuyền gỗ dài. Thuyền có cánh buồm vuông lớn.', [['sail', 'buồm; đi thuyền'], ['ship', 'tàu thuyền'], ['square', 'hình vuông']]] } },
    peru: { country: 'Peru', vi: 'Peru', spots: {
      machupicchu: ['Machu Picchu', 'Machu Picchu', 'Machu Picchu is an old Inca city high in the mountains. It was built more than five hundred years ago.', 'Machu Picchu là thành phố cổ của người Inca trên núi cao. Nó được xây hơn năm trăm năm trước.', [['mountain', 'núi'], ['ancient', 'cổ xưa'], ['city', 'thành phố']]],
      andeanhouse: ['An Andean house', 'Nhà vùng Andes', 'Many families in the Andes live in stone houses. They keep llamas and alpacas near their homes.', 'Nhiều gia đình vùng Andes sống trong nhà đá. Họ nuôi lạc đà llama và alpaca gần nhà.', [['stone', 'đá'], ['family', 'gia đình'], ['llama', 'lạc đà llama']]],
      panflute: ['The panpipes', 'Sáo pan', 'Panpipes are made of many tubes of different lengths. You blow across the top to make music.', 'Sáo pan gồm nhiều ống có độ dài khác nhau. Bạn thổi ngang miệng ống để tạo ra âm nhạc.', [['tube', 'ống'], ['blow', 'thổi'], ['music', 'âm nhạc']]],
      quipu: ['The quipu', 'Quipu (dây thắt nút)', 'The Incas used a quipu to keep records. It is made of strings with knots.', 'Người Inca dùng quipu để ghi chép. Nó làm từ những sợi dây có thắt nút.', [['string', 'sợi dây'], ['knot', 'nút thắt'], ['record', 'ghi chép']]] } },
    argentina: { country: 'Argentina', vi: 'Argentina', spots: {
      perito: ['Perito Moreno Glacier', 'Sông băng Perito Moreno', 'Perito Moreno is a huge glacier in Patagonia. It is made of blue and white ice.', 'Perito Moreno là sông băng khổng lồ ở Patagonia. Nó được tạo nên từ băng xanh và trắng.', [['glacier', 'sông băng'], ['ice', 'băng'], ['huge', 'khổng lồ']]],
      laboca: ['La Boca', 'Khu La Boca', 'La Boca is a neighbourhood in Buenos Aires. Its houses are painted in many bright colours.', 'La Boca là một khu phố ở Buenos Aires. Những ngôi nhà ở đây được sơn nhiều màu rực rỡ.', [['neighbourhood', 'khu phố'], ['bright', 'rực rỡ'], ['paint', 'sơn']]],
      mategourd: ['Mate', 'Trà mate', 'Mate is a hot drink from yerba leaves. People share it with friends from one cup and a metal straw.', 'Mate là thức uống nóng làm từ lá yerba. Mọi người chia sẻ nó từ một chiếc cốc và ống hút kim loại.', [['leaf', 'lá cây'], ['share', 'chia sẻ'], ['straw', 'ống hút']]],
      bandoneon: ['The bandoneon', 'Đàn bandoneon', 'The bandoneon is a small instrument like an accordion. It is often played with tango music.', 'Bandoneon là nhạc cụ nhỏ giống đàn accordion. Nó thường được chơi trong nhạc tango.', [['instrument', 'nhạc cụ'], ['accordion', 'đàn accordion'], ['tango', 'điệu tango']]] } },
    cuba: { country: 'Cuba', vi: 'Cuba', spots: {
      capitolio: ['El Capitolio', 'Toà nhà Capitolio', 'El Capitolio is a famous building in Havana. It has a big dome on the top.', 'El Capitolio là toà nhà nổi tiếng ở Havana. Nó có mái vòm lớn ở trên cùng.', [['dome', 'mái vòm'], ['famous', 'nổi tiếng'], ['building', 'toà nhà']]],
      vintagecar: ['Classic cars', 'Xe cổ', 'Many old American cars from the 1950s still drive in Cuba. People paint them in bright colours.', 'Nhiều chiếc xe Mỹ cũ từ thập niên 1950 vẫn chạy ở Cuba. Người ta sơn chúng bằng màu rực rỡ.', [['classic', 'cổ điển'], ['drive', 'lái xe'], ['colour', 'màu sắc']]],
      cuflag: ['The flag of Cuba', 'Quốc kỳ Cuba', 'The flag of Cuba has blue and white stripes. There is a red triangle with a white star.', 'Quốc kỳ Cuba có các sọc xanh và trắng. Có một tam giác đỏ với ngôi sao trắng.', [['stripe', 'sọc'], ['triangle', 'tam giác'], ['star', 'ngôi sao']]],
      congadrum: ['The conga drum', 'Trống conga', 'The conga is a tall drum used in Cuban music. People play it with their hands.', 'Conga là loại trống cao dùng trong nhạc Cuba. Người ta chơi nó bằng tay.', [['drum', 'cái trống'], ['tall', 'cao'], ['hand', 'bàn tay']]] } },
    chile: { country: 'Chile', vi: 'Chile', spots: {
      moai: ['Moai statues', 'Tượng moai', 'Moai are giant stone heads on Easter Island. They belong to Chile.', 'Moai là những cái đầu đá khổng lồ trên đảo Phục Sinh. Đảo thuộc về Chile.', [['stone', 'đá'], ['island', 'hòn đảo'], ['giant', 'khổng lồ']]],
      palafito: ['Palafito houses', 'Nhà palafito', 'Palafitos are colourful houses on wooden poles above the water. You can see them on the island of Chiloé.', 'Palafito là những ngôi nhà nhiều màu trên cột gỗ phía trên mặt nước. Bạn có thể thấy chúng trên đảo Chiloé.', [['pole', 'cột'], ['wooden', 'bằng gỗ'], ['water', 'nước']]],
      clflag: ['The flag of Chile', 'Quốc kỳ Chile', 'The flag of Chile has a white stripe and a red stripe. There is a white star in a blue square.', 'Quốc kỳ Chile có một sọc trắng và một sọc đỏ. Có ngôi sao trắng trong ô vuông xanh.', [['stripe', 'sọc'], ['square', 'ô vuông'], ['star', 'ngôi sao']]],
      copihue: ['The copihue', 'Hoa copihue', 'The copihue is the national flower of Chile. It is a red bell-shaped flower.', 'Copihue là quốc hoa của Chile. Đó là loài hoa đỏ hình chiếc chuông.', [['flower', 'hoa'], ['national', 'thuộc quốc gia'], ['bell', 'cái chuông']]] } },
    kenya: { country: 'Kenya', vi: 'Kenya', spots: {
      kilimanjaro: ['Mount Kilimanjaro', 'Núi Kilimanjaro', 'Mount Kilimanjaro is the tallest mountain in Africa. People in Kenya can see it from Amboseli National Park.', 'Kilimanjaro là ngọn núi cao nhất châu Phi. Người ở Kenya có thể nhìn thấy nó từ Vườn quốc gia Amboseli.', [['mountain', 'núi'], ['tallest', 'cao nhất'], ['park', 'công viên']]],
      maasaiboma: ['A Maasai village', 'Làng Maasai', 'The Maasai people live in villages called bomas. Their houses are made of sticks, mud and grass.', 'Người Maasai sống trong những ngôi làng gọi là boma. Nhà của họ làm từ que, bùn và cỏ.', [['village', 'ngôi làng'], ['mud', 'bùn'], ['grass', 'cỏ']]],
      maasaishield: ['A Maasai shield', 'Khiên của người Maasai', 'The Maasai make shields with red, black and white colours. Warriors carry them.', 'Người Maasai làm khiên với các màu đỏ, đen và trắng. Chiến binh mang theo chúng.', [['shield', 'cái khiên'], ['warrior', 'chiến binh'], ['carry', 'mang theo']]],
      safarijeep: ['A safari jeep', 'Xe jeep đi safari', 'People take a jeep on a safari to see wild animals like lions and giraffes.', 'Người ta đi xe jeep trong chuyến safari để xem thú hoang như sư tử và hươu cao cổ.', [['safari', 'chuyến safari'], ['wild', 'hoang dã'], ['animal', 'con vật']]] } },
    southafrica: { country: 'South Africa', vi: 'Nam Phi', spots: {
      tablemountain: ['Table Mountain', 'Núi Bàn', 'Table Mountain is a flat mountain above Cape Town. You can ride a cable car to the top.', 'Núi Bàn là ngọn núi phẳng phía trên Cape Town. Bạn có thể đi cáp treo lên đỉnh.', [['flat', 'phẳng'], ['cable car', 'cáp treo'], ['top', 'đỉnh']]],
      ndebele: ['Ndebele house paintings', 'Nhà vẽ hoa văn Ndebele', 'Ndebele women paint their houses with bright shapes and colours.', 'Phụ nữ Ndebele vẽ nhà bằng những hình khối và màu sắc rực rỡ.', [['paint', 'sơn, vẽ'], ['shape', 'hình dạng'], ['bright', 'rực rỡ']]],
      vuvuzela: ['The vuvuzela', 'Kèn vuvuzela', 'A vuvuzela is a long plastic horn. Football fans blow it and make a loud sound.', 'Vuvuzela là chiếc kèn nhựa dài. Cổ động viên bóng đá thổi nó và tạo ra âm thanh rất to.', [['horn', 'cái kèn'], ['fan', 'người hâm mộ'], ['loud', 'to, ồn']]],
      proteaflower: ['The king protea', 'Hoa protea vua', 'The king protea is the national flower of South Africa. It looks like a big, pink crown.', 'Protea vua là quốc hoa của Nam Phi. Nó trông như một chiếc vương miện hồng lớn.', [['flower', 'hoa'], ['crown', 'vương miện'], ['national', 'thuộc quốc gia']]] } },
    ethiopia: { country: 'Ethiopia', vi: 'Ethiopia', spots: {
      lalibela: ['The churches of Lalibela', 'Nhà thờ đá Lalibela', 'The churches of Lalibela are cut into rock. They are more than 800 years old.', 'Các nhà thờ Lalibela được đục vào đá. Chúng hơn 800 năm tuổi.', [['rock', 'tảng đá'], ['church', 'nhà thờ'], ['old', 'cổ, lâu đời']]],
      tukul: ['A tukul', 'Nhà tukul', 'A tukul is a round house with a grass roof. Many families in the countryside live in one.', 'Tukul là ngôi nhà tròn có mái cỏ. Nhiều gia đình ở nông thôn sống trong nhà như vậy.', [['round', 'hình tròn'], ['roof', 'mái nhà'], ['countryside', 'nông thôn']]],
      jebena: ['The coffee ceremony', 'Nghi lễ cà phê', 'Ethiopia is the home of coffee. People make coffee in a clay pot called a jebena and share it with guests.', 'Ethiopia là quê hương của cà phê. Người ta pha cà phê trong bình đất sét gọi là jebena và mời khách.', [['coffee', 'cà phê'], ['guest', 'khách'], ['clay', 'đất sét']]],
      meskelcross: ['The Ethiopian cross', 'Thập giá Ethiopia', 'Ethiopian crosses are made of metal and have beautiful patterns. People carry them in festivals.', 'Thập giá Ethiopia làm bằng kim loại và có hoạ tiết đẹp. Mọi người mang chúng trong các lễ hội.', [['metal', 'kim loại'], ['pattern', 'hoạ tiết'], ['festival', 'lễ hội']]] } },
    madagascar: { country: 'Madagascar', vi: 'Madagascar', spots: {
      baobabs: ['The Avenue of the Baobabs', 'Đại lộ cây bao báp', 'The Avenue of the Baobabs is a famous road with very tall baobab trees. It is in Madagascar.', 'Đại lộ cây bao báp là con đường nổi tiếng với những cây bao báp rất cao. Nó ở Madagascar.', [['road', 'con đường'], ['tall', 'cao'], ['tree', 'cái cây']]],
      tsingy: ['Tsingy', 'Rừng đá Tsingy', 'Tsingy is a forest of sharp stone needles. It is in Madagascar.', 'Tsingy là khu rừng của những mũi đá nhọn như kim. Nó ở Madagascar.', [['sharp', 'sắc nhọn'], ['stone', 'đá'], ['forest', 'khu rừng']]],
      mgflag: ['The flag of Madagascar', 'Quốc kỳ Madagascar', 'The flag of Madagascar has white, red and green. White is on the left.', 'Quốc kỳ Madagascar có màu trắng, đỏ và xanh lá. Màu trắng ở bên trái.', [['left', 'bên trái'], ['green', 'xanh lá'], ['red', 'màu đỏ']]],
      vanilla: ['Vanilla', 'Vani', 'Madagascar grows a lot of vanilla. Vanilla comes from the pod of an orchid.', 'Madagascar trồng rất nhiều vani. Vani lấy từ quả của một loài lan.', [['pod', 'quả, vỏ quả'], ['orchid', 'hoa lan'], ['grow', 'trồng']]] } }
  };
  var API = { CULTURE: C, IDS: Object.keys(C) };
  if (typeof module !== 'undefined' && module.exports) module.exports = API; else root.EWTCulture = API;
})(typeof window !== 'undefined' ? window : this);
