/* EWT Garden — Hộ chiếu văn hoá: thông tin tiếng Anh về từng công trình của 15 khu quốc gia (dùng ở trình duyệt).
   Mỗi khu có 4 điểm chạm (công trình biểu tượng, công trình văn hoá, cờ, vật phẩm). Mỗi điểm: [tên EN, tên VI, câu tiếng Anh (A2), dịch VI, [[từ, nghĩa], …]].
   Câu hỏi mini-quiz (có đáp án) nằm ở máy chủ: garden-culture-quiz.js. Chỉ ghi những điều chắc chắn đúng. */
(function (root) {
  'use strict';
  var C = {
    vietnam: { country: 'Vietnam', vi: 'Việt Nam', spots: {
      onepillar: ['One Pillar Pagoda', 'Chùa Một Cột', 'The One Pillar Pagoda stands on a single stone pillar in a pond in Hanoi. It was built in 1049.', 'Chùa Một Cột đứng trên một cột đá duy nhất giữa hồ ở Hà Nội. Chùa được xây năm 1049.', [['pagoda', 'chùa'], ['pillar', 'cột'], ['pond', 'ao, hồ nhỏ']]],
      hoianhouse: ['Hoi An Ancient Town', 'Phố cổ Hội An', 'Hoi An is famous for its yellow houses and colourful lanterns. It is a UNESCO World Heritage Site.', 'Hội An nổi tiếng với những ngôi nhà vàng và đèn lồng nhiều màu. Đây là Di sản Thế giới của UNESCO.', [['lantern', 'đèn lồng'], ['ancient', 'cổ xưa'], ['heritage', 'di sản']]],
      vnflag: ['The flag of Vietnam', 'Quốc kỳ Việt Nam', 'The flag of Vietnam is red with a yellow star in the middle.', 'Quốc kỳ Việt Nam màu đỏ với ngôi sao vàng ở giữa.', [['flag', 'lá cờ'], ['star', 'ngôi sao'], ['middle', 'ở giữa']]],
      conicalhat: ['Conical hat (nón lá)', 'Nón lá', 'A conical hat is made from palm leaves. It protects people from the sun and the rain.', 'Nón lá được làm từ lá cọ. Nón che nắng và che mưa cho người đội.', [['conical', 'hình nón'], ['palm leaf', 'lá cọ'], ['protect', 'bảo vệ']]] } },
    thailand: { country: 'Thailand', vi: 'Thái Lan', spots: {
      wat: ['Thai temple (wat)', 'Chùa Thái (wat)', 'A Thai temple is called a wat. Many wats have golden towers and colourful roofs.', 'Chùa ở Thái Lan gọi là wat. Nhiều ngôi chùa có tháp vàng và mái nhà nhiều màu.', [['temple', 'ngôi chùa, đền'], ['golden', 'bằng vàng, vàng óng'], ['roof', 'mái nhà']]],
      floatmarket: ['Floating market', 'Chợ nổi', 'At a floating market, people sell fruit and food from small boats.', 'Ở chợ nổi, người ta bán trái cây và đồ ăn trên những chiếc thuyền nhỏ.', [['market', 'chợ'], ['boat', 'thuyền'], ['sell', 'bán']]],
      thflag: ['The flag of Thailand', 'Quốc kỳ Thái Lan', 'The flag of Thailand has five horizontal stripes: red, white, blue, white and red. The blue stripe is in the middle and is the widest.', 'Quốc kỳ Thái Lan có năm sọc ngang: đỏ, trắng, xanh, trắng, đỏ. Sọc xanh ở giữa và rộng nhất.', [['stripe', 'sọc'], ['horizontal', 'nằm ngang'], ['wide', 'rộng']]],
      thelephant: ['The elephant', 'Con voi', 'The elephant is the national animal of Thailand.', 'Voi là quốc thú của Thái Lan.', [['elephant', 'con voi'], ['national', 'thuộc quốc gia'], ['animal', 'động vật']]] } },
    japan: { country: 'Japan', vi: 'Nhật Bản', spots: {
      fuji: ['Mount Fuji', 'Núi Phú Sĩ', 'Mount Fuji is the highest mountain in Japan. It is 3,776 metres tall.', 'Núi Phú Sĩ là ngọn núi cao nhất Nhật Bản. Núi cao 3.776 mét.', [['mountain', 'ngọn núi'], ['highest', 'cao nhất'], ['tall', 'cao']]],
      japancastle: ['Japanese castle', 'Lâu đài Nhật Bản', 'Himeji Castle is a famous white castle in Japan. People call it the White Heron Castle.', 'Lâu đài Himeji là một lâu đài trắng nổi tiếng ở Nhật Bản. Người ta gọi nó là Lâu đài Diệc Trắng.', [['castle', 'lâu đài'], ['heron', 'con diệc'], ['famous', 'nổi tiếng']]],
      jpflag: ['The flag of Japan', 'Quốc kỳ Nhật Bản', 'The flag of Japan is white with a red circle. The circle is the sun.', 'Quốc kỳ Nhật Bản màu trắng với hình tròn đỏ. Hình tròn là mặt trời.', [['circle', 'hình tròn'], ['sun', 'mặt trời'], ['white', 'màu trắng']]],
      maneki: ['Maneki-neko (lucky cat)', 'Mèo may mắn', 'The maneki-neko is a lucky cat. It raises its paw to bring good luck.', 'Maneki-neko là chú mèo may mắn. Mèo giơ chân lên để mang lại vận may.', [['lucky', 'may mắn'], ['paw', 'bàn chân thú'], ['raise', 'giơ lên']]] } },
    china: { country: 'China', vi: 'Trung Quốc', spots: {
      greatwall: ['The Great Wall', 'Vạn Lý Trường Thành', 'The Great Wall of China is more than 20,000 kilometres long. People built it to protect the country.', 'Vạn Lý Trường Thành dài hơn 20.000 km. Người ta xây nó để bảo vệ đất nước.', [['wall', 'bức tường'], ['protect', 'bảo vệ'], ['kilometre', 'ki-lô-mét']]],
      chinapagoda: ['Chinese pagoda', 'Tháp chùa Trung Quốc', 'A pagoda is a tall tower with many roofs. It is often part of a temple.', 'Pagoda là toà tháp cao có nhiều tầng mái. Nó thường là một phần của ngôi chùa.', [['pagoda', 'tháp chùa'], ['tower', 'toà tháp'], ['roof', 'mái nhà']]],
      cnflag: ['The flag of China', 'Quốc kỳ Trung Quốc', 'The flag of China is red with five yellow stars. One star is big and four stars are small.', 'Quốc kỳ Trung Quốc màu đỏ với năm ngôi sao vàng. Một sao lớn và bốn sao nhỏ.', [['star', 'ngôi sao'], ['yellow', 'màu vàng'], ['small', 'nhỏ']]],
      cnlantern: ['Red lantern', 'Đèn lồng đỏ', 'People hang red lanterns during Chinese New Year. Red is a lucky colour in China.', 'Người ta treo đèn lồng đỏ trong dịp Tết Trung Quốc. Màu đỏ là màu may mắn ở Trung Quốc.', [['lantern', 'đèn lồng'], ['hang', 'treo'], ['lucky', 'may mắn']]] } },
    india: { country: 'India', vi: 'Ấn Độ', spots: {
      tajmahal: ['The Taj Mahal', 'Đền Taj Mahal', 'The Taj Mahal is in the city of Agra. A king built it for his wife, Mumtaz Mahal.', 'Taj Mahal ở thành phố Agra. Một vị vua xây nó cho vợ mình, Mumtaz Mahal.', [['king', 'vua'], ['wife', 'vợ'], ['dome', 'mái vòm']]],
      tuktuk: ['Tuk-tuk', 'Xe tuk-tuk', 'A tuk-tuk is a small three-wheeled taxi. It is popular in India and Thailand.', 'Tuk-tuk là loại taxi nhỏ ba bánh. Nó phổ biến ở Ấn Độ và Thái Lan.', [['wheel', 'bánh xe'], ['taxi', 'xe taxi'], ['popular', 'phổ biến']]],
      inflag: ['The flag of India', 'Quốc kỳ Ấn Độ', 'The flag of India has three colours: orange, white and green. A blue wheel is in the middle.', 'Quốc kỳ Ấn Độ có ba màu: cam, trắng và xanh lá. Giữa cờ có một bánh xe màu xanh dương.', [['wheel', 'bánh xe'], ['orange', 'màu cam'], ['green', 'xanh lá']]],
      diya: ['Diya lamp', 'Đèn dầu diya', 'A diya is a small oil lamp. People light diyas at the festival of Diwali.', 'Diya là chiếc đèn dầu nhỏ. Người ta thắp diya trong lễ hội Diwali.', [['lamp', 'cái đèn'], ['light', 'thắp sáng'], ['festival', 'lễ hội']]] } },
    indonesia: { country: 'Indonesia', vi: 'Indonesia', spots: {
      borobudur: ['Borobudur Temple', 'Đền Borobudur', 'Borobudur is the largest Buddhist temple in the world. It is on the island of Java.', 'Borobudur là ngôi đền Phật giáo lớn nhất thế giới. Nó nằm trên đảo Java.', [['temple', 'ngôi đền'], ['largest', 'lớn nhất'], ['island', 'hòn đảo']]],
      baligate: ['Balinese split gate', 'Cổng chẻ Bali', 'A split gate looks like a tower cut into two halves. You can see it at temples in Bali.', 'Cổng chẻ trông như một tháp bị cắt làm đôi. Bạn có thể thấy nó ở các đền thờ ở Bali.', [['gate', 'cổng'], ['half', 'một nửa'], ['tower', 'toà tháp']]],
      idflag: ['The flag of Indonesia', 'Quốc kỳ Indonesia', 'The flag of Indonesia has two stripes. The top is red and the bottom is white.', 'Quốc kỳ Indonesia có hai sọc. Sọc trên màu đỏ và sọc dưới màu trắng.', [['top', 'phía trên'], ['bottom', 'phía dưới'], ['stripe', 'sọc']]],
      wayang: ['Wayang puppet', 'Rối bóng wayang', 'Wayang is a traditional puppet show. The puppets make shadows on a white screen.', 'Wayang là nghệ thuật múa rối truyền thống. Những con rối tạo bóng trên màn trắng.', [['puppet', 'con rối'], ['shadow', 'cái bóng'], ['traditional', 'truyền thống']]] } },
    france: { country: 'France', vi: 'Pháp', spots: {
      eiffel: ['The Eiffel Tower', 'Tháp Eiffel', 'The Eiffel Tower is in Paris. It was built in 1889 for a big world fair.', 'Tháp Eiffel ở Paris. Tháp được xây năm 1889 cho một hội chợ thế giới lớn.', [['tower', 'toà tháp'], ['build', 'xây dựng'], ['fair', 'hội chợ']]],
      cafe: ['French café', 'Quán cà phê Pháp', 'In France, many people drink coffee and eat a croissant at a café.', 'Ở Pháp, nhiều người uống cà phê và ăn bánh sừng bò ở quán cà phê.', [['café', 'quán cà phê'], ['croissant', 'bánh sừng bò'], ['coffee', 'cà phê']]],
      frflag: ['The flag of France', 'Quốc kỳ Pháp', 'The flag of France has three vertical stripes: blue, white and red.', 'Quốc kỳ Pháp có ba sọc dọc: xanh dương, trắng và đỏ.', [['vertical', 'thẳng đứng'], ['blue', 'xanh dương'], ['stripe', 'sọc']]],
      baguette: ['Baguette', 'Bánh mì baguette', 'A baguette is a long, thin French bread. It is crispy outside and soft inside.', 'Baguette là loại bánh mì Pháp dài và mỏng. Vỏ giòn bên ngoài và ruột mềm bên trong.', [['bread', 'bánh mì'], ['crispy', 'giòn'], ['soft', 'mềm']]] } },
    italy: { country: 'Italy', vi: 'Ý', spots: {
      colosseum: ['The Colosseum', 'Đấu trường Colosseum', 'The Colosseum is in Rome. In ancient times, people watched gladiator fights there.', 'Colosseum ở Rome. Thời cổ đại, người ta xem các trận đấu của đấu sĩ ở đó.', [['ancient', 'cổ xưa'], ['gladiator', 'đấu sĩ'], ['fight', 'trận đấu, cuộc chiến']]],
      pizzeria: ['Pizzeria', 'Tiệm pizza', 'A pizzeria is a restaurant that makes pizza in a very hot oven.', 'Pizzeria là nhà hàng làm pizza trong lò rất nóng.', [['oven', 'lò nướng'], ['restaurant', 'nhà hàng'], ['dough', 'bột nhào']]],
      itflag: ['The flag of Italy', 'Quốc kỳ Ý', 'The flag of Italy is green, white and red. The stripes are vertical.', 'Quốc kỳ Ý gồm xanh lá, trắng và đỏ. Các sọc thẳng đứng.', [['green', 'xanh lá'], ['vertical', 'thẳng đứng'], ['stripe', 'sọc']]],
      pizza: ['Pizza', 'Bánh pizza', 'Pizza comes from Naples, a city in Italy. A classic pizza has tomato and cheese.', 'Pizza bắt nguồn từ Naples, một thành phố ở Ý. Pizza truyền thống có cà chua và phô mai.', [['cheese', 'phô mai'], ['tomato', 'cà chua'], ['slice', 'miếng, lát']]] } },
    netherlands: { country: 'the Netherlands', vi: 'Hà Lan', spots: {
      dutchwindmill: ['Dutch windmill', 'Cối xay gió Hà Lan', 'A windmill uses the wind to turn its big blades. In the Netherlands, windmills helped pump water from the land.', 'Cối xay gió dùng gió để quay những cánh lớn. Ở Hà Lan, cối xay gió giúp bơm nước khỏi đất.', [['blade', 'cánh quạt'], ['pump', 'bơm'], ['wind', 'gió']]],
      tulipfield: ['Tulip field', 'Cánh đồng tulip', 'In spring, the Netherlands has colourful tulip fields. The tulip is a famous Dutch flower.', 'Mùa xuân, Hà Lan có những cánh đồng tulip rực rỡ. Hoa tulip là loài hoa nổi tiếng của Hà Lan.', [['tulip', 'hoa tulip'], ['spring', 'mùa xuân'], ['field', 'cánh đồng']]],
      nlflag: ['The flag of the Netherlands', 'Quốc kỳ Hà Lan', 'The flag of the Netherlands has three horizontal stripes: red, white and blue.', 'Quốc kỳ Hà Lan có ba sọc ngang: đỏ, trắng và xanh dương.', [['horizontal', 'nằm ngang'], ['red', 'màu đỏ'], ['blue', 'xanh dương']]],
      woodenshoe: ['Wooden shoes (klompen)', 'Guốc gỗ (klompen)', 'Wooden shoes are called klompen in Dutch. Farmers wore them to keep their feet dry.', 'Giày gỗ tiếng Hà Lan gọi là klompen. Nông dân đi chúng để giữ cho chân khô ráo.', [['wooden', 'bằng gỗ'], ['farmer', 'nông dân'], ['dry', 'khô']]] } },
    uk: { country: 'the United Kingdom', vi: 'Vương quốc Anh', spots: {
      bigben: ['Big Ben', 'Tháp Big Ben', 'Big Ben is the nickname of the great bell in the clock tower in London.', 'Big Ben là biệt danh của chiếc chuông lớn trong tháp đồng hồ ở London.', [['bell', 'cái chuông'], ['clock', 'đồng hồ'], ['nickname', 'biệt danh']]],
      doubledecker: ['Double-decker bus', 'Xe buýt hai tầng', 'A double-decker bus has two floors. Red buses are a symbol of London.', 'Xe buýt hai tầng có hai tầng. Xe buýt đỏ là biểu tượng của London.', [['floor', 'tầng'], ['symbol', 'biểu tượng'], ['bus', 'xe buýt']]],
      ukflag: ['The Union Jack', 'Cờ Union Jack', 'The Union Jack is the flag of the United Kingdom. It joins the crosses of England, Scotland and Ireland.', 'Union Jack là quốc kỳ của Vương quốc Anh. Nó kết hợp các chữ thập của Anh, Scotland và Ireland.', [['cross', 'chữ thập'], ['join', 'kết hợp'], ['flag', 'lá cờ']]],
      phonebox: ['Red telephone box', 'Hộp điện thoại đỏ', 'Red telephone boxes are a famous sight in the UK. People used them to make phone calls in the street.', 'Hộp điện thoại đỏ là hình ảnh nổi tiếng ở Anh. Người ta dùng chúng để gọi điện ngoài phố.', [['telephone', 'điện thoại'], ['sight', 'cảnh tượng'], ['street', 'đường phố']]] } },
    germany: { country: 'Germany', vi: 'Đức', spots: {
      brandenburg: ['Brandenburg Gate', 'Cổng Brandenburg', 'The Brandenburg Gate is a famous monument in Berlin. It is a symbol of peace and unity.', 'Cổng Brandenburg là công trình nổi tiếng ở Berlin. Nó là biểu tượng của hoà bình và thống nhất.', [['gate', 'cổng'], ['monument', 'đài kỷ niệm'], ['unity', 'sự thống nhất']]],
      bavarianhouse: ['Half-timbered house', 'Nhà khung gỗ', 'Many old German houses have wooden beams in their walls. We call them half-timbered houses.', 'Nhiều ngôi nhà cổ ở Đức có xà gỗ trong tường. Ta gọi đó là nhà khung gỗ.', [['beam', 'xà gỗ'], ['wooden', 'bằng gỗ'], ['wall', 'bức tường']]],
      deflag: ['The flag of Germany', 'Quốc kỳ Đức', 'The flag of Germany has three horizontal stripes: black, red and gold.', 'Quốc kỳ Đức có ba sọc ngang: đen, đỏ và vàng.', [['black', 'màu đen'], ['gold', 'màu vàng kim'], ['stripe', 'sọc']]],
      pretzel: ['Pretzel', 'Bánh pretzel', 'A pretzel is a baked bread in a twisted shape. It is popular in Germany.', 'Pretzel là loại bánh mì nướng có hình xoắn. Nó phổ biến ở Đức.', [['twisted', 'xoắn'], ['baked', 'được nướng'], ['shape', 'hình dạng']]] } },
    usa: { country: 'the United States', vi: 'Hoa Kỳ', spots: {
      liberty: ['Statue of Liberty', 'Tượng Nữ thần Tự do', 'France gave the Statue of Liberty to the United States. It stands in New York Harbor.', 'Nước Pháp tặng Tượng Nữ thần Tự do cho Hoa Kỳ. Tượng đứng ở cảng New York.', [['statue', 'bức tượng'], ['liberty', 'tự do'], ['harbor', 'bến cảng']]],
      yellowcab: ['Yellow taxi', 'Taxi vàng', 'Yellow taxis are a symbol of New York City.', 'Taxi vàng là biểu tượng của thành phố New York.', [['taxi', 'xe taxi'], ['symbol', 'biểu tượng'], ['city', 'thành phố']]],
      usflag: ['The flag of the USA', 'Quốc kỳ Hoa Kỳ', 'The flag of the United States has 50 stars and 13 stripes. The stars are for the states, and the stripes are for the first colonies.', 'Quốc kỳ Hoa Kỳ có 50 ngôi sao và 13 sọc. Các sao tượng trưng cho các bang, các sọc tượng trưng cho các thuộc địa đầu tiên.', [['state', 'bang'], ['stripe', 'sọc'], ['colony', 'thuộc địa']]],
      hotdog: ['Hot dog', 'Bánh mì xúc xích', 'A hot dog is a sausage in a soft bun. It is a popular fast food in the USA.', 'Hot dog là xúc xích kẹp trong bánh mì mềm. Đây là món ăn nhanh phổ biến ở Mỹ.', [['sausage', 'xúc xích'], ['bun', 'bánh mì tròn'], ['fast food', 'đồ ăn nhanh']]] } },
    greece: { country: 'Greece', vi: 'Hy Lạp', spots: {
      parthenon: ['The Parthenon', 'Đền Parthenon', 'The Parthenon is an ancient temple on the Acropolis in Athens. It was built for the goddess Athena.', 'Parthenon là ngôi đền cổ trên đồi Acropolis ở Athens. Nó được xây cho nữ thần Athena.', [['temple', 'ngôi đền'], ['goddess', 'nữ thần'], ['ancient', 'cổ xưa']]],
      santorini: ['Santorini', 'Đảo Santorini', 'Santorini is a Greek island. It is famous for its white houses with blue domes.', 'Santorini là một hòn đảo của Hy Lạp. Đảo nổi tiếng với những ngôi nhà trắng có mái vòm xanh.', [['island', 'hòn đảo'], ['dome', 'mái vòm'], ['famous', 'nổi tiếng']]],
      grflag: ['The flag of Greece', 'Quốc kỳ Hy Lạp', 'The flag of Greece has blue and white stripes and a white cross in the corner.', 'Quốc kỳ Hy Lạp có các sọc xanh và trắng cùng một chữ thập trắng ở góc.', [['corner', 'góc'], ['cross', 'chữ thập'], ['stripe', 'sọc']]],
      amphora: ['Amphora', 'Bình amphora', 'An amphora is a tall clay jar. In ancient Greece, people used it to store oil and wine.', 'Amphora là chiếc bình đất sét cao. Ở Hy Lạp cổ đại, người ta dùng nó để chứa dầu và rượu vang.', [['clay', 'đất sét'], ['jar', 'cái bình'], ['store', 'cất giữ']]] } },
    sweden: { country: 'Sweden', vi: 'Thụy Điển', spots: {
      redcottage: ['Red wooden house', 'Nhà gỗ đỏ', 'Many Swedish houses are painted red with white corners. The red colour is called Falu red.', 'Nhiều ngôi nhà ở Thụy Điển được sơn đỏ với góc trắng. Màu đỏ đó gọi là đỏ Falu.', [['cottage', 'nhà nhỏ ở nông thôn'], ['paint', 'sơn'], ['corner', 'góc']]],
      dalahorse: ['Dala horse', 'Ngựa Dala', 'The Dala horse is a small wooden horse from Sweden. It is painted red with colourful patterns.', 'Ngựa Dala là con ngựa gỗ nhỏ của Thụy Điển. Nó được sơn đỏ với hoa văn nhiều màu.', [['wooden', 'bằng gỗ'], ['pattern', 'hoa văn'], ['painted', 'được sơn']]],
      seflag: ['The flag of Sweden', 'Quốc kỳ Thụy Điển', 'The flag of Sweden is blue with a yellow cross.', 'Quốc kỳ Thụy Điển màu xanh dương với chữ thập vàng.', [['cross', 'chữ thập'], ['yellow', 'màu vàng'], ['blue', 'xanh dương']]],
      cinnamonbun: ['Cinnamon bun', 'Bánh quế cinnamon', 'A cinnamon bun is a sweet roll with cinnamon. Swedes eat it with coffee during fika, a coffee break.', 'Bánh cuộn quế là loại bánh ngọt có quế. Người Thụy Điển ăn nó với cà phê trong giờ fika, giờ nghỉ uống cà phê.', [['cinnamon', 'quế'], ['sweet', 'ngọt'], ['roll', 'bánh cuộn']]] } },
    switzerland: { country: 'Switzerland', vi: 'Thụy Sĩ', spots: {
      matterhorn: ['The Matterhorn', 'Đỉnh Matterhorn', 'The Matterhorn is a famous mountain in the Alps. It is on the border between Switzerland and Italy.', 'Matterhorn là ngọn núi nổi tiếng trong dãy Alps. Núi nằm ở biên giới giữa Thụy Sĩ và Ý.', [['border', 'biên giới'], ['peak', 'đỉnh núi'], ['mountain', 'ngọn núi']]],
      swisschalet: ['Swiss chalet', 'Nhà gỗ chalet', 'A chalet is a wooden house in the mountains. It often has a wide roof and flower boxes.', 'Chalet là ngôi nhà gỗ trên núi. Nhà thường có mái rộng và những chậu hoa.', [['chalet', 'nhà gỗ miền núi'], ['wide', 'rộng'], ['roof', 'mái nhà']]],
      chflag: ['The flag of Switzerland', 'Quốc kỳ Thụy Sĩ', 'The flag of Switzerland is red with a white cross. It is square.', 'Quốc kỳ Thụy Sĩ màu đỏ với chữ thập trắng. Lá cờ có hình vuông.', [['square', 'hình vuông'], ['cross', 'chữ thập'], ['red', 'màu đỏ']]],
      cuckooclock: ['Cuckoo clock', 'Đồng hồ cúc cu', 'A cuckoo clock has a small bird that comes out and sings every hour.', 'Đồng hồ cúc cu có một chú chim nhỏ chui ra và hót mỗi giờ.', [['cuckoo', 'chim cúc cu'], ['hour', 'giờ'], ['sing', 'hót, hát']]] } }
  };
  var API = { CULTURE: C, IDS: Object.keys(C) };
  if (typeof module !== 'undefined' && module.exports) module.exports = API; else root.EWTCulture = API;
})(typeof window !== 'undefined' ? window : this);
