'use strict';
// Đề viết ngắn. Task 1 (A2, ≥25 từ): email theo 3 ý — lấy từ KET for Schools Trainer, Part 6.
// Task 2 (B1+, ~100 từ): bài viết ngắn (article) — lấy từ B1 Preliminary for Schools Trainer, Writing Part 2 (câu 2).
const { writing } = require('./lib');
const K = (n) => 'Cambridge A2 Key for Schools Trainer · Test ' + n + ' · Reading & Writing Part 6';
const P = (n) => 'Cambridge B1 Preliminary for Schools Trainer · Test ' + n + ' · Writing Part 2 (Question 2)';

module.exports = [
  writing('w1-ket1', 'A2', "Read this email from your English friend, Francis.\n\nFrom: Francis\nSubject: This weekend\n\nHi,\nIt's great that you're free to meet me this weekend. I have a few questions. Where is the best place in your town to meet? What would you like to do? And shall I bring anything?\nWrite soon!\nFrancis\n\nWrite an email to Francis and answer his questions.", 25, K(1), { task: 1 }),
  writing('w1-ket2', 'A2', "Read the email from your English friend Sam.\n\nFrom: Sam\nSubject: Help! I'm bored!\n\nHi,\nI want to ask you something. I'm really bored. Can I borrow something to read from you? What do you think I will enjoy? And when would you like it back?\nI hope that's OK. Cheers!\nSam\n\nWrite an email to Sam and answer the questions.", 25, K(2), { task: 1 }),
  writing('w1-ket3', 'A2', "You are planning a party. Write an email to your English friend Malcolm.\n\nIn your email:\n• tell Malcolm about your party\n• ask if Malcolm wants to come\n• suggest what Malcolm should bring.", 25, K(3), { task: 1 }),
  writing('w1-ket4', 'A2', "You recently lost something when you were in town with your English friend Alfie. Write an email to Alfie.\n\nIn your email:\n• say what you have lost\n• explain how you think you lost it\n• tell Alfie what you want him to do to help.", 25, K(4), { task: 1 }),
  writing('w1-ket5', 'A2', "Read the email from your English friend Liam.\n\nFrom: Liam\n\nHi,\nI'm going to be in your town next week. Could you tell me about a good place to eat? What's the food like? Where is it?\nThanks.\nLiam\n\nWrite an email to Liam and answer the questions.", 25, K(5), { task: 1 }),
  writing('w1-ket6', 'A2', "Read the email from your English friend Joe.\n\nFrom: Joe\n\nHi,\nSorry, I know I said I can meet you tomorrow afternoon, but I can't. Can we meet next week instead? When are you free? And where is a good place to meet?\nCheers,\nJoe\n\nWrite an email to Joe and answer the questions.", 25, K(6), { task: 1 }),

  writing('w2-pet1', 'B1', "You see this notice in your school English-language magazine.\n\nArticles wanted!\nFRIENDSHIP\nWrite an article telling us how important it is for friends to have similar characters.\nDo you think it's better to have lots of friends or just one best friend? Why?\nThe best articles answering these questions will be published next month.\n\nWrite your article.", 80, P(1), { task: 2 }),
  writing('w2-pet3', 'B1', "You see this notice in your school English-language magazine.\n\nArticles wanted!\nBEING HEALTHY\nWrite an article about young people and healthy living. Is it important for young people to do sport and to keep fit? Why?\nWhat are some fun ways to stay healthy?\nThe best articles answering these questions will be published next month.\n\nWrite your article.", 80, P(3), { task: 2 }),
  writing('w2-pet4', 'B1', "You see this notice on an international English website for young people.\n\nArticles wanted!\nFESTIVALS\nWrite an article telling us about a festival that you or your family celebrate. When does the festival take place, and what happens?\nWhat do you like about it?\nThe best articles answering these questions will be published next month.\n\nWrite your article.", 80, P(4), { task: 2 }),
  writing('w2-pet5', 'B1', "You see this notice in your school English-language magazine.\n\nArticles wanted!\nSHOPPING\nWrite an article telling us whether you like shopping and where your family usually goes shopping.\nDoes your family buy things online? Why or why not?\nThe best articles answering these questions will be published next month.\n\nWrite your article.", 80, P(5), { task: 2 }),
  writing('w2-pet6', 'B1', "You see this notice on an international English website for young people.\n\nArticles wanted!\nMUSIC LOVERS!\nWrite an article telling us what your favourite kind of music is and when you listen to it. Is music important in your life? Why?\nWhat is the best way to find new songs or artists?\nThe best articles answering these questions will be published next month.\n\nWrite your article.", 80, P(6), { task: 2 }),
];
